(in-package #:cl-tensor)

(defun zeros (shape &key (dtype :f32))
  (make-tensor shape :dtype dtype))

(defun full (shape value &key (dtype :f32))
  (computational-dtype dtype)
  (let ((value (coerce-value value dtype))
        (result (make-tensor shape :dtype dtype)))
    (require-writable-storage result)
    (if (backend-storage-p (tensor-storage result))
        (trivial-simd:fill! (tensor-storage result) value)
        (dotimes (i (tensor-size result))
          (setf (storage-ref (tensor-storage result) i) value)))
    result))

(defun ones (shape &key (dtype :f32))
  (full shape 1 :dtype dtype))

(defun from-data (data &key (dtype :f32))
  (computational-dtype dtype)
  (let ((values nil))
    (labels ((leaf (value)
               (push (coerce-value value dtype) values))
             (walk (value)
               (cond ((numberp value) (leaf value) nil)
                     ((or (listp value) (and (vectorp value) (not (stringp value))))
                      (let ((shape nil) (firstp t))
                        (map nil (lambda (item)
                                   (let ((child (walk item)))
                                     (if firstp
                                         (setf shape child firstp nil)
                                         (unless (equal shape child)
                                           (error "Data must be rectangular"))))) value)
                        (cons (length value) shape)))
                     ((arrayp value)
                      (dotimes (i (array-total-size value))
                        (leaf (row-major-aref value i)))
                      (array-dimensions value))
                     (t (error "Expected numeric data, got ~S" value)))))
      (let* ((shape (walk data))
             (result (make-tensor shape :dtype dtype)))
        (require-writable-storage result)
        (loop for value in (nreverse values) for i from 0
              do (setf (storage-ref (tensor-storage result) i) value))
        result))))

(defun arange (&rest arguments)
  (let* ((split (or (position-if #'keywordp arguments) (length arguments)))
         (bounds (subseq arguments 0 split)))
    (destructuring-bind (&key (dtype :f32)) (nthcdr split arguments)
      (computational-dtype dtype)
      (unless (<= 1 (length bounds) 3)
        (error "ARANGE needs stop, start/stop, or start/stop/step"))
      (let* ((start (if (= (length bounds) 1) 0 (first bounds)))
             (stop (if (= (length bounds) 1) (first bounds) (second bounds)))
             (step (if (= (length bounds) 3) (third bounds) 1)))
        (unless (and (realp start) (realp stop) (realp step) (not (zerop step)))
          (error "ARANGE bounds must be real and step must be nonzero"))
        (let* ((count (cl:max 0 (ceiling (/ (- (rational stop) (rational start))
                                          (rational step)))))
               (result (make-tensor (list count) :dtype dtype)))
          (require-writable-storage result)
          (dotimes (i count result)
            (setf (storage-ref (tensor-storage result) i)
                  (coerce-value (+ start (* i step)) dtype))))))))

(defun linspace (start stop &key (num 50) (endpoint t) (dtype :f32))
  (unless (and (realp start) (realp stop) (typep num '(integer 0 #.most-positive-fixnum))
               (member dtype '(:f32 :f64)))
    (error "LINSPACE needs real bounds, a nonnegative sample count, and :f32 or :f64"))
  (let ((result (make-tensor (list num) :dtype dtype)))
    (require-writable-storage result)
    (dotimes (i num result)
      (setf (storage-ref (tensor-storage result) i)
            (coerce-value (cond ((zerop i) start)
                                ((and endpoint (= i (1- num))) stop)
                                (t (+ (* (- 1 (/ i (if endpoint (1- num) num))) start)
                                      (* (/ i (if endpoint (1- num) num)) stop))))
                          dtype)))))

(defun eye (rows &key (columns rows) (k 0) (dtype :f32))
  (computational-dtype dtype)
  (unless (integerp k) (error "EYE diagonal offset must be an integer"))
  (let ((result (make-tensor (list rows columns) :dtype dtype))
        (one (coerce-value 1 dtype)))
    (require-writable-storage result)
    (loop for row from (cl:max 0 (- k)) below (cl:min rows (- columns k))
          do (setf (storage-ref (tensor-storage result) (+ (* row columns) row k)) one))
    result))
