(in-package #:cl-tensor)

(defun broadcast-shape (operands)
  (let* ((tensors (remove-if-not #'tensorp operands))
         (rank (reduce #'cl:max tensors :key #'tensor-rank :initial-value 0))
         (shape (make-array rank :element-type 'fixnum :initial-element 1)))
    (dolist (tensor tensors shape)
      (loop for dimension across (tensor-shape tensor)
            for axis from (- rank (tensor-rank tensor))
            for current = (aref shape axis)
            do (cond ((= dimension current))
                     ((= current 1) (setf (aref shape axis) dimension))
                     ((/= dimension 1)
                      (error "Incompatible broadcast shapes")))))))

(defun broadcast-strides (tensor shape)
  (let* ((rank (length shape))
         (strides (make-array rank :element-type 'fixnum :initial-element 0)))
    (loop for dimension across (tensor-shape tensor)
          for stride across (tensor-strides tensor)
          for axis from (- rank (tensor-rank tensor))
          unless (= dimension 1) do (setf (aref strides axis) stride))
    strides))

(defun unique-output-p (tensor)
  (when (<= (tensor-size tensor) 1) (return-from unique-output-p t))
  (let ((axes (sort (loop for dimension across (tensor-shape tensor)
                          for stride across (tensor-strides tensor)
                          when (> dimension 1) collect (cons (cl:abs stride) dimension))
                    #'< :key #'car))
        (extent 0))
    (when (loop for (stride . dimension) in axes
                always (> stride extent)
                do (incf extent (* stride (1- dimension))))
      (return-from unique-output-p t)))
  ;; TODO: O(size) workspace for irregular layouts; add arithmetic proofs (#25).
  (let ((seen (make-hash-table :test #'eql)))
    (call-with-offsets (tensor-shape tensor) (list (tensor-strides tensor))
                       (list (tensor-offset tensor))
                       (lambda (index)
                         (when (gethash index seen) (return-from unique-output-p nil))
                         (setf (gethash index seen) t)))
    t))

(defun storage-span (tensor)
  (multiple-value-bind (low high)
      (reachable-range (tensor-shape tensor) (tensor-strides tensor) (tensor-offset tensor))
    (let* ((storage (tensor-storage tensor))
           (size (dtype-bytes (tensor-dtype tensor)))
           (base (if (trivial-simd:vector-view-p storage)
                     (cffi:pointer-address (trivial-simd:vector-view-pointer storage))
                     0)))
      (values (+ base (* low size)) (+ base (* (1+ high) size))))))

(defun overlapping-p (a b)
  (when (or (zerop (tensor-size a)) (zerop (tensor-size b)))
    (return-from overlapping-p nil))
  (let ((sa (tensor-storage a)) (sb (tensor-storage b)))
    ;; TODO: mixed storage always snapshots; prove disjointness with pinned addresses (#26).
    (when (not (eq (trivial-simd:vector-view-p sa) (trivial-simd:vector-view-p sb)))
      (return-from overlapping-p t))
    (when (or (eq sa sb)
              (and (trivial-simd:vector-view-p sa) (trivial-simd:vector-view-p sb)))
      (multiple-value-bind (al ah) (storage-span a)
        (multiple-value-bind (bl bh) (storage-span b)
          (and (< al bh) (< bl ah)))))))

(defun nd-function (operation)
  (ecase operation
    (:add #'trivial-simd:nd-add!) (:subtract #'trivial-simd:nd-subtract!)
    (:multiply #'trivial-simd:nd-multiply!) (:divide #'trivial-simd:nd-divide!)
    (:negate #'trivial-simd:nd-negate!) (:abs #'trivial-simd:nd-abs!)
    (:sqrt #'trivial-simd:nd-sqrt!) (:reciprocal #'trivial-simd:nd-reciprocal!)
    (:min #'trivial-simd:nd-min!) (:max #'trivial-simd:nd-max!)
    (:clamp #'trivial-simd:nd-clamp!) (:compare #'trivial-simd:nd-compare!)
    (:select #'trivial-simd:nd-select!) (:astype #'trivial-simd:nd-convert!)))

(defun nd-keywords (operation)
  (ecase operation
    ((:add :subtract :multiply :divide :min :max :compare)
     '((:left-start :left-strides) (:right-start :right-strides)))
    ((:negate :abs :sqrt :reciprocal :astype) '((:input-start :input-strides)))
    (:clamp '((:input-start :input-strides) (:lower-start :lower-strides) (:upper-start :upper-strides)))
    (:select '((:mask-start :mask-strides) (:true-start :true-strides) (:false-start :false-strides)))))

(defun run-nd (operation out operands &key operator rounding)
  (let* ((shape (tensor-shape out))
         (keywords (list (if (eq operation :compare) :mask-start :destination-start) (tensor-offset out)
                         (if (eq operation :compare) :mask-strides :destination-strides) (tensor-strides out))))
    (loop for input in operands for (start strides) in (nd-keywords operation)
          when (tensorp input) do
            (setf keywords (list* start (tensor-offset input) strides (broadcast-strides input shape) keywords)))
    (when (eq operation :astype)
      (setf keywords (list* :rounding rounding keywords))
      (when (dtype-storage-only-p (tensor-dtype (first operands)))
        (setf keywords (list* :input-encoding (tensor-dtype (first operands)) keywords)))
      (when (dtype-storage-only-p (tensor-dtype out))
        (setf keywords (list* :destination-encoding (tensor-dtype out) keywords))))
    (apply (nd-function operation) (tensor-storage out)
           (append (when (eq operation :compare) (list operator))
                   (mapcar (lambda (input) (if (tensorp input) (tensor-storage input) input)) operands)
                   (list shape) keywords)))
  out)

(defun check-operation (operation dtype operator)
  (computational-dtype dtype)
  (when (and (member operation '(:sqrt :reciprocal))
             (not (member dtype '(:f32 :f64 :c32 :c64))))
    (error "~S requires a floating-point dtype" operation))
  (when (and (member dtype '(:c32 :c64)) (member operation '(:min :max :clamp)))
    (error "Complex values have no ordering"))
  (when (eq operation :compare)
    (unless (member operator '(:eq :ne :lt :le :gt :ge))
      (error "Unknown comparison operator ~S" operator))
    (when (and (member dtype '(:c32 :c64)) (not (member operator '(:eq :ne))))
      (error "Complex values support only equality comparisons"))))

(defun elementwise (operation out operands &key dtype operator)
  (when out (check-type out tensor))
  (let* ((numeric (if (eq operation :select) (rest operands) operands))
         (context (find-if #'tensorp numeric))
         (dtype (or (and context (tensor-dtype context)) dtype (and out (tensor-dtype out))
                    (error "A numeric tensor or explicit dtype is required")))
         (shape (broadcast-shape operands))
         (result-dtype (cond ((eq operation :compare) :u8)
                             ((and (eq operation :abs) (eq dtype :c32)) :f32)
                             ((and (eq operation :abs) (eq dtype :c64)) :f64)
                             (t dtype))))
    (check-operation operation dtype operator)
    (when (eq operation :select)
      (unless (and (tensorp (first operands)) (eq :u8 (tensor-dtype (first operands))))
        (error "SELECT needs a :u8 tensor mask")))
    (setf numeric
          (mapcar (lambda (input)
                    (if (tensorp input)
                        (progn (unless (eq dtype (tensor-dtype input))
                                 (error "Mixed tensor dtypes require ASTYPE")) input)
                        (coerce-value input dtype))) numeric))
    (when (and (eq operation :clamp) (numberp (second numeric)) (numberp (third numeric))
               (> (second numeric) (third numeric)))
      (error "CLAMP lower bound exceeds upper bound"))
    (let ((result (or out (make-tensor shape :dtype result-dtype))))
      (unless (and (equalp shape (tensor-shape result)) (eq result-dtype (tensor-dtype result)))
        (error "Output must have shape ~S and dtype ~S" shape result-dtype))
      (run-nd operation result
                (if (eq operation :select) (cons (first operands) numeric) numeric)
                :operator operator))))

(defmacro define-elementwise (name operation arguments)
  (let ((out-name (intern (format nil "~A!" name))))
    `(progn
       (defun ,name ,arguments
         (elementwise ,operation nil (list ,@arguments)))
       (defun ,out-name (out ,@arguments)
         (check-type out tensor)
         (elementwise ,operation out (list ,@arguments))))))

(define-elementwise add :add (a b))
(define-elementwise subtract :subtract (a b))
(define-elementwise multiply :multiply (a b))
(define-elementwise divide :divide (a b))
(define-elementwise min :min (a b))
(define-elementwise max :max (a b))
(define-elementwise negate :negate (input))
(define-elementwise abs :abs (input))
(define-elementwise sqrt :sqrt (input))
(define-elementwise reciprocal :reciprocal (input))
(define-elementwise clamp :clamp (input lower upper))

(defun compare (operator a b)
  (elementwise :compare nil (list a b) :operator operator))

(defun compare! (out operator a b)
  (check-type out tensor)
  (elementwise :compare out (list a b) :operator operator))

(defun select (mask on-true on-false &key (dtype nil dtype-p))
  (when dtype-p
    (computational-dtype dtype)
    (dolist (input (list on-true on-false))
      (when (and (tensorp input) (not (eq dtype (tensor-dtype input))))
        (error "Explicit dtype must match numeric tensor operands"))))
  (elementwise :select nil (list mask on-true on-false) :dtype dtype))

(defun select! (out mask on-true on-false)
  (check-type out tensor)
  (elementwise :select out (list mask on-true on-false)))

(defun astype (tensor dtype &key (rounding :nearest-even))
  (check-type tensor tensor)
  (find-dtype dtype)
  (unless (member rounding '(:nearest-even :truncate :floor :ceiling))
    (error "Unknown conversion rounding mode ~S" rounding))
  (when (or (dtype-storage-only-p dtype) (dtype-storage-only-p (tensor-dtype tensor)))
    (unless (and (member dtype '(:f32 :f64 :f16 :bf16))
                 (member (tensor-dtype tensor) '(:f32 :f64 :f16 :bf16)))
      (error "Encoded conversion requires real floats or encoded storage")))
  (run-nd :astype (make-tensor (tensor-shape tensor) :dtype dtype)
            (list tensor) :rounding rounding))
