(in-package #:cl-tensor)

(defun matmul-promote (tensor left)
  (if (/= (tensor-rank tensor) 1)
      tensor
      (make-tensor-view (tensor-storage tensor)
                        (if left (list 1 (tensor-size tensor)) (list (tensor-size tensor) 1))
                        :dtype (tensor-dtype tensor) :offset (tensor-offset tensor)
                        :strides (if left (list 0 (aref (tensor-strides tensor) 0))
                                     (list (aref (tensor-strides tensor) 0) 0)))))

(defun matmul-batch-view (tensor)
  (let ((rank (- (tensor-rank tensor) 2)))
    ;; Metadata only: empty matrices can have nonempty batches and out-of-storage offsets.
    (%make-tensor (tensor-storage tensor) (tensor-dtype tensor)
                  (subseq (tensor-shape tensor) 0 rank)
                  (subseq (tensor-strides tensor) 0 rank) (tensor-offset tensor))))

(defun matmul-matrix-layout (rows cols rs cs)
  (cond ((and (or (= cols 1) (= cs 1))
              (or (= rows 1) (<= (cl:max 1 cols) rs)))
         (values :row-major (if (= rows 1) (cl:max 1 cols) rs)))
        ((and (or (= rows 1) (= rs 1))
              (or (= cols 1) (<= (cl:max 1 rows) cs)))
         (values :column-major (if (= cols 1) (cl:max 1 rows) cs)))))

(defun matmul-copy-matrix (tensor offset rows cols rs cs buffer scatter)
  (dotimes (i rows)
    (dotimes (j cols)
      (let ((index (+ offset (* i rs) (* j cs))) (position (+ (* i cols) j)))
        (if scatter
            (setf (storage-ref (tensor-storage tensor) index) (aref buffer position))
            (setf (aref buffer position) (storage-ref (tensor-storage tensor) index)))))))

(defun matmul-matrix-adapter (tensor &optional output)
  (let* ((axis (- (tensor-rank tensor) 2))
         (rows (aref (tensor-shape tensor) axis))
         (cols (aref (tensor-shape tensor) (1+ axis)))
         (rs (aref (tensor-strides tensor) axis))
         (cs (aref (tensor-strides tensor) (1+ axis))))
    (multiple-value-bind (layout ld) (matmul-matrix-layout rows cols rs cs)
      (when ld
        (unless (typep ld 'trivial-simd/blas::blas-dim)
          (error "Matrix leading dimension exceeds BLAS limits")))
      (let* ((scratch (unless layout
                        (make-array (* rows cols) :element-type (dtype-element-type (tensor-dtype tensor))
                                                 :initial-element (dtype-zero (tensor-dtype tensor)))))
             (transpose (if (and (not output) (eq layout :column-major))
                            :transpose :no-transpose)))
        (values
         (lambda (offset)
           (when (and scratch (not output))
             (matmul-copy-matrix tensor offset rows cols rs cs scratch nil))
           (trivial-simd/blas:make-matrix-view
            (or scratch (tensor-storage tensor))
            (if (eq transpose :transpose) cols rows)
            (if (eq transpose :transpose) rows cols)
            :layout (if output (or layout :row-major) :row-major)
            :leading-dimension (or ld (cl:max 1 cols)) :offset (if scratch 0 offset)))
         transpose
         (when (and output scratch)
           (lambda (offset)
             (matmul-copy-matrix tensor offset rows cols rs cs scratch t))))))))

(defun matmul-vector-adapter (tensor axis &optional output)
  (let* ((count (aref (tensor-shape tensor) axis))
         (stride (if (= count 1) 1 (aref (tensor-strides tensor) axis)))
         (scratch (when (zerop stride)
                    (when output (error "Matmul output elements overlap"))
                    (make-array count :element-type (dtype-element-type (tensor-dtype tensor)))))
         (increment (if scratch 1 stride)))
    (unless (typep increment 'trivial-simd/blas::blas-increment)
      (error "Vector stride exceeds BLAS limits"))
    (lambda (offset)
      (when scratch (fill scratch (storage-ref (tensor-storage tensor) offset)))
      (values (or scratch (tensor-storage tensor)) increment
              (if scratch 0 (+ offset (if (minusp stride) (* (1- count) stride) 0)))))))

(defun matmul-run (a b out batch k left-vector right-vector)
  (let* ((dtype (tensor-dtype a))
         (single (eq dtype :f32))
         (one (coerce-value 1 dtype))
         (zero (dtype-zero dtype))
         (ab (matmul-batch-view a)) (bb (matmul-batch-view b))
         (ob (matmul-batch-view out))
         (layouts (list (broadcast-strides ab batch) (broadcast-strides bb batch)
                        (tensor-strides ob)))
         (offsets (list (tensor-offset a) (tensor-offset b) (tensor-offset out))))
    (multiple-value-bind (aa ta)
        (if left-vector
            (matmul-vector-adapter a (1- (tensor-rank a)))
            (matmul-matrix-adapter a))
      (multiple-value-bind (ba tb)
          (if right-vector
              (matmul-vector-adapter b (- (tensor-rank b) 2))
              (matmul-matrix-adapter b))
        (multiple-value-bind (oa ignored scatter)
            (cond ((and left-vector right-vector) (values nil nil nil))
                  ((or left-vector right-vector)
                   (matmul-vector-adapter out
                                          (if left-vector (1- (tensor-rank out))
                                              (- (tensor-rank out) 2)) t))
                  (t (matmul-matrix-adapter out t)))
          (declare (ignore ignored))
          ;; TODO: one BLAS call per batch; adopt strided-batched GEMM (#17).
          (call-with-offsets
           batch layouts offsets
           (lambda (ai bi oi)
             (cond
               ((and left-vector right-vector)
                (multiple-value-bind (av inc-a start-a) (funcall aa ai)
                  (multiple-value-bind (bv inc-b start-b) (funcall ba bi)
                    (setf (storage-ref (tensor-storage out) oi)
                          (funcall (if single #'trivial-simd/blas:sdot #'trivial-simd/blas:ddot)
                                   k av inc-a bv inc-b :x-offset start-a :y-offset start-b)))))
               ((or left-vector right-vector)
                (multiple-value-bind (vector increment start)
                    (if left-vector (funcall aa ai) (funcall ba bi))
                  (multiple-value-bind (target target-increment target-start) (funcall oa oi)
                    (funcall (if single #'trivial-simd/blas:sgemv #'trivial-simd/blas:dgemv)
                             (if left-vector
                                 (if (eq tb :transpose) :no-transpose :transpose) ta)
                             one (if left-vector (funcall ba bi) (funcall aa ai))
                             vector increment zero target target-increment
                             :x-offset start :y-offset target-start))))
               (t
                (funcall (if single #'trivial-simd/blas:sgemm #'trivial-simd/blas:dgemm)
                         ta tb one (funcall aa ai) (funcall ba bi) zero (funcall oa oi))
                (when scatter (funcall scatter oi))))))))))
  out)

(defun tensor-matmul (a b out)
  (check-type a tensor)
  (check-type b tensor)
  (when out (check-type out tensor))
  (unless (and (plusp (tensor-rank a)) (plusp (tensor-rank b)))
    (error "Matmul operands must have rank at least one"))
  (unless (and (member (tensor-dtype a) '(:f32 :f64))
               (eq (tensor-dtype a) (tensor-dtype b)))
    (error "Matmul requires matching :f32 or :f64 dtypes; convert with ASTYPE"))
  (let* ((left-vector (= (tensor-rank a) 1))
         (right-vector (= (tensor-rank b) 1))
         (ap (matmul-promote a t)) (bp (matmul-promote b nil))
         (ar (- (tensor-rank ap) 2)) (br (- (tensor-rank bp) 2))
         (m (aref (tensor-shape ap) ar)) (k (aref (tensor-shape ap) (1+ ar)))
         (n (aref (tensor-shape bp) (1+ br)))
         (batch (broadcast-shape (list (matmul-batch-view ap) (matmul-batch-view bp))))
         (shape (index-vector (append (coerce batch 'list)
                                     (unless left-vector (list m)) (unless right-vector (list n))))))
    (unless (= k (aref (tensor-shape bp) br))
      (error "Matmul contraction dimensions must match"))
    (unless (every (lambda (dimension) (typep dimension 'trivial-simd/blas::blas-dim)) (list m k n))
      (error "Matmul dimensions exceed BLAS limits"))
    (let ((result (or out (make-tensor shape :dtype (tensor-dtype a)))))
      (unless (and (equalp shape (tensor-shape result)) (eq (tensor-dtype a) (tensor-dtype result)))
        (error "Matmul output must have shape ~S and dtype ~S" shape (tensor-dtype a)))
      (unless (unique-output-p result) (error "Matmul output elements overlap"))
      (when (zerop (tensor-size result)) (return-from tensor-matmul result))
      (when (zerop k)
        (call-with-offsets shape (list (tensor-strides result)) (list (tensor-offset result))
                           (lambda (index)
                             (setf (storage-ref (tensor-storage result) index) (dtype-zero (tensor-dtype a)))))
        (return-from tensor-matmul result))
      (dolist (tensor (list a b result))
        (multiple-value-bind (low high)
            (reachable-range (tensor-shape tensor) (tensor-strides tensor) (tensor-offset tensor))
          (declare (ignore low))
          (unless (typep high 'trivial-simd/blas::blas-offset)
            (error "Matmul storage offsets exceed BLAS limits"))))
      (when (overlapping-p result a) (setf ap (matmul-promote (copy-tensor a) t)))
      (when (overlapping-p result b) (setf bp (matmul-promote (copy-tensor b) nil)))
      (let* ((strides (coerce (tensor-strides result) 'list))
             (batch-rank (length batch))
             (matrix-strides (append (subseq strides 0 batch-rank)
                                     (list (if left-vector 0 (nth batch-rank strides))
                                           (if right-vector 0 (car (last strides))))))
             (output (make-tensor-view (tensor-storage result)
                                       (append (coerce batch 'list) (list m n))
                                       :dtype (tensor-dtype result) :offset (tensor-offset result)
                                       :strides matrix-strides)))
        (matmul-run ap bp output batch k left-vector right-vector))
      result)))

(defun matmul (a b)
  (tensor-matmul a b nil))

(defun matmul! (out a b)
  (check-type out tensor)
  (tensor-matmul a b out))
