(in-package #:cl-tensor)

(defmacro define-normalization-rows ()
  `(progn
     ,@(loop for dtype in '(:f32 :f64)
             for type in '(single-float double-float)
             for foreign in '(:float :double)
             append
             (loop for wide in (if (eq dtype :f32) '(nil t) '(nil))
                   for sum-type = (if wide 'double-float type)
                   collect
                   `(defun ,(intern (format nil "NORMALIZATION-ROW-~A-~A" dtype (if wide "WIDE" "SAME")))
                        (operation destination input input-start destination-start width epsilon)
                      (declare (type (simple-array ,type (*)) destination)
                               (type fixnum input-start destination-start width)
                               (type ,type epsilon)
                               (optimize (speed 3) (safety 1)))
                      (let ((pointer (when (trivial-simd:vector-view-p input)
                                       (trivial-simd:vector-view-pointer input)))
                            (total ,(coerce 0 sum-type)))
                        (declare (type ,sum-type total))
                        (macrolet ((read-input (index)
                                     `(if pointer
                                          (cffi:mem-aref pointer ,',foreign ,index)
                                          (aref (the (simple-array ,',type (*)) input) ,index))))
                          (ecase operation
                            (:softmax
                             (let ((maximum (trivial-simd:maximum input :input-start input-start :end width)))
                               (declare (type ,type maximum))
                               (dotimes (i width)
                                 (let ((value (exp (- (read-input (+ input-start i)) maximum))))
                                   (setf (aref destination (+ destination-start i)) value)
                                   (incf total (coerce value ',sum-type))))
                               (let ((inverse (coerce (/ ,(coerce 1 sum-type) total) ',type)))
                                 (dotimes (i width)
                                   (setf (aref destination (+ destination-start i))
                                         (* (aref destination (+ destination-start i)) inverse))))))
                            (:rmsnorm
                             (dotimes (i width)
                               (let ((x (read-input (+ input-start i))))
                                 (incf total (coerce (* x x) ',sum-type))))
                             (let ((scale (/ ,(coerce 1 type)
                                             (cl:sqrt (+ epsilon (coerce (/ total width) ',type))))))
                               (declare (type ,type scale))
                               (dotimes (i width)
                                 (setf (aref destination (+ destination-start i))
                                       (* (read-input (+ input-start i)) scale)))))))))))))

(define-normalization-rows)

(defun normalization-row-function (dtype accumulate)
  (ecase dtype
    (:f32 (if accumulate #'normalization-row-f32-wide #'normalization-row-f32-same))
    (:f64 #'normalization-row-f64-same)))

(defun normalization-weights (weights input)
  (cond ((null weights) nil)
        ((tensorp weights)
         (unless (eq (tensor-dtype weights) (tensor-dtype input))
           (error "RMSNorm weight dtype must match input"))
         (unless (equalp (broadcast-shape (list input weights)) (tensor-shape input))
           (error "RMSNorm weights must broadcast to the input shape"))
         weights)
        (t (coerce-value weights (tensor-dtype input)))))

(defun tensor-normalization (operation input out axis accumulate weights epsilon)
  (check-type input tensor)
  (when out (check-type out tensor))
  (let* ((dtype (tensor-dtype input))
         (rank (tensor-rank input))
         (axes (if (null axis) (loop for a below rank collect a) (normalize-axes axis rank))))
    (unless (member dtype '(:f32 :f64))
      (error "Normalization requires :F32 or :F64"))
    (unless (member accumulate '(nil :f64))
      (error "Normalization accumulation must be NIL or :F64"))
    (unless (and (realp epsilon) (>= epsilon 0))
      (error "RMSNorm epsilon must be a nonnegative real"))
    (setf epsilon (coerce-value epsilon dtype)
          weights (normalization-weights weights input))
    (when out
      (unless (and (equalp (tensor-shape out) (tensor-shape input))
                   (eq (tensor-dtype out) dtype))
        (error "Normalization output shape or dtype does not match"))
      (unless (unique-output-p out) (error "Normalization output elements overlap")))
    (when (zerop (tensor-size input))
      (return-from tensor-normalization (or out (make-tensor (tensor-shape input) :dtype dtype))))
    (multiple-value-bind (shape width kept) (reduction-layout input axes nil)
      (let* ((rows (reduce #'* shape))
             (order (append kept axes))
             (matrix (reduction-rows input axes kept width rows))
             ;; TODO: O(input size) scratch; use bounded rows for proven-disjoint outputs (#30).
             (scratch (make-tensor (list rows width) :dtype dtype))
             (runner (normalization-row-function dtype accumulate)))
        (dotimes (row rows)
          (funcall runner operation (tensor-storage scratch) (tensor-storage matrix)
                   (+ (tensor-offset matrix) (* row (aref (tensor-strides matrix) 0)))
                   (* row width) width epsilon))
        (let* ((grouped (reshape scratch (tensor-shape (transpose input :axes order))))
               (inverse (loop for a below rank collect (position a order)))
               (normalized (transpose grouped :axes inverse)))
          ;; TODO: Lisp f64 weight/copy stages box per element; use typed traversal (#30).
          (when weights (multiply! normalized normalized weights))
          (cond (out (run-nd :astype out (list normalized) :rounding :nearest-even))
                ((contiguous-p normalized) (reshape normalized (tensor-shape input)))
                (t (copy-tensor normalized))))))))

(defun softmax (input &key (axis -1) accumulate)
  (tensor-normalization :softmax input nil axis accumulate nil 0))

(defun softmax! (out input &key (axis -1) accumulate)
  (check-type out tensor)
  (tensor-normalization :softmax input out axis accumulate nil 0))

(defun rmsnorm (input &key (axis -1) weights (epsilon 1e-6) accumulate)
  (tensor-normalization :rmsnorm input nil axis accumulate weights epsilon))

(defun rmsnorm! (out input &key (axis -1) weights (epsilon 1e-6) accumulate)
  (check-type out tensor)
  (tensor-normalization :rmsnorm input out axis accumulate weights epsilon))
