(in-package #:cl-tensor)

(trivial-simd:define-kernel reduction-sum (input) (trivial-simd:sum input))
(trivial-simd:define-kernel reduction-product (input) (trivial-simd:prod input))
(trivial-simd:define-kernel reduction-minimum (input) (trivial-simd:minimum input))
(trivial-simd:define-kernel reduction-maximum (input) (trivial-simd:maximum input))
(trivial-simd:define-kernel reduction-argmin (input) (trivial-simd:argmin input))
(trivial-simd:define-kernel reduction-argmax (input) (trivial-simd:argmax input))

(defun reduction-functions (operation)
  (ecase operation
    ((:sum :mean) (values #'trivial-simd:sum #'reduction-sum))
    (:prod (values #'trivial-simd:prod #'reduction-product))
    (:minimum (values #'trivial-simd:minimum #'reduction-minimum))
    (:maximum (values #'trivial-simd:maximum #'reduction-maximum))
    (:argmin (values #'trivial-simd:argmin #'reduction-argmin))
    (:argmax (values #'trivial-simd:argmax #'reduction-argmax))))

(defun reduction-dtype (operation dtype accumulate)
  (computational-dtype dtype)
  (when (and (member operation '(:minimum :maximum :argmin :argmax))
             (member dtype '(:c32 :c64)))
    (error "Complex values have no ordering"))
  (when accumulate
    (unless (and (eq accumulate :f64) (member operation '(:sum :mean))
                 (member dtype '(:f32 :f64 :c32 :c64)))
      (error "Widened accumulation requires a float or complex SUM/MEAN")))
  (cond ((member operation '(:argmin :argmax)) :s64)
        ((and (eq operation :mean) (not (member dtype '(:f32 :f64 :c32 :c64)))) :f64)
        ((and accumulate (eq dtype :f32)) :f64)
        ((and accumulate (eq dtype :c32)) :c64)
        (t dtype)))

(defun reduction-layout (tensor axes keepdims)
  (let* ((shape (tensor-shape tensor))
         (kept (loop for a below (tensor-rank tensor) unless (member a axes) collect a))
         (result-shape (if keepdims
                           (loop for d across shape for a from 0 collect (if (member a axes) 1 d))
                           (mapcar (lambda (a) (aref shape a)) kept)))
         (width (reduce #'* axes :key (lambda (a) (aref shape a)) :initial-value 1)))
    (values (index-vector result-shape) width kept)))

;; TODO: O(input size) packing; use bounded staging or native stride descriptors (#27).
(defun reduction-rows (tensor axes kept width rows)
  (let* ((order (append kept axes))
         (grouped (transpose tensor :axes order))
         (matrix (reshape grouped (list rows width))))
    (if (or (<= width 1) (= 1 (aref (tensor-strides matrix) 1)))
        matrix
        (copy-tensor matrix))))

(defun tensor-reduction (operation tensor out axis keepdims accumulate)
  (check-type tensor tensor)
  (when out (check-type out tensor))
  (let* ((axes (if (null axis) (loop for a below (tensor-rank tensor) collect a)
                   (normalize-axes axis (tensor-rank tensor))))
         (dtype (reduction-dtype operation (tensor-dtype tensor) accumulate)))
    (multiple-value-bind (shape width kept) (reduction-layout tensor axes keepdims)
      (let* ((rows (reduce #'* shape))
             (result (or out (make-tensor shape :dtype dtype))))
        (unless (and (equalp shape (tensor-shape result)) (eq dtype (tensor-dtype result)))
          (error "Reduction output shape or dtype does not match"))
        (unless (unique-output-p result) (error "Reduction output elements overlap"))
        (when (and (plusp rows) (zerop width)
                   (member operation '(:mean :minimum :maximum :argmin :argmax)))
          (error "Empty reduction groups have no ~S" operation))
        (when (zerop rows) (return-from tensor-reduction result))
        (let* ((input-dtype (if (member operation '(:argmin :argmax)) (tensor-dtype tensor) dtype))
               (input (if (eq input-dtype (tensor-dtype tensor)) tensor (astype tensor input-dtype)))
               ;; TODO: O(output size) scratch; write proven-disjoint outputs directly (#27).
               (values (if out
                           (make-array rows :element-type (dtype-element-type dtype)
                                            :initial-element (dtype-zero dtype))
                           (tensor-storage result))))
          (when (and (zerop width) (eq operation :prod))
            (fill values (coerce-value 1 dtype)))
          (unless (zerop width)
            (multiple-value-bind (scalar batch) (reduction-functions operation)
              (if (and (null kept) (contiguous-p input))
                  (let* ((offset (tensor-offset input))
                         (value (funcall scalar (tensor-storage input) :input-start offset :end width)))
                    (setf (aref values 0) (if (member operation '(:argmin :argmax)) (- value offset) value)))
                  (let ((matrix (reduction-rows input axes kept width rows)))
                    (funcall batch (tensor-storage matrix) :rows rows :row-length width
                                   :input-start (tensor-offset matrix)
                                   :input-row-stride (aref (tensor-strides matrix) 0)
                                   :destination values)))))
          (when (eq operation :mean)
            (dotimes (i rows) (setf (aref values i) (/ (aref values i) width))))
          (when out
            (let ((position 0))
            (call-with-offsets shape (list (tensor-strides result)) (list (tensor-offset result))
                               (lambda (index)
                                 (setf (storage-ref (tensor-storage result) index) (aref values position))
                                 (incf position)))))
          result)))))

(defmacro define-tensor-reduction (name operation &optional accumulation-p)
  (let ((out-name (intern (format nil "~A!" name))))
    `(progn
       (defun ,name (tensor &key axis keepdims ,@(when accumulation-p '(accumulate)))
         (tensor-reduction ,operation tensor nil axis keepdims ,(when accumulation-p 'accumulate)))
       (defun ,out-name (out tensor &key axis keepdims ,@(when accumulation-p '(accumulate)))
         (tensor-reduction ,operation tensor out axis keepdims ,(when accumulation-p 'accumulate))))))

(define-tensor-reduction sum :sum t)
(define-tensor-reduction mean :mean t)
(define-tensor-reduction prod :prod)
(define-tensor-reduction minimum :minimum)
(define-tensor-reduction maximum :maximum)
(define-tensor-reduction argmin :argmin)
(define-tensor-reduction argmax :argmax)
