(in-package #:cl-tensor)

(defun normalize-axis (axis rank)
  (unless (and (integerp axis) (<= (- rank) axis) (< axis rank))
    (error "Axis ~S is outside rank ~D" axis rank))
  (if (minusp axis) (+ rank axis) axis))

(defun normalize-axes (axis rank)
  (let ((axes (if (integerp axis) (list axis) (coerce axis 'list))))
    (setf axes (mapcar (lambda (a) (normalize-axis a rank)) axes))
    (unless (= (length axes) (length (remove-duplicates axes)))
      (error "Duplicate axes: ~S" axis))
    (sort axes #'<)))

(defun layout-view (tensor shape strides &optional (offset (tensor-offset tensor)))
  (make-tensor-view (tensor-storage tensor) shape :dtype (tensor-dtype tensor)
                    :strides strides :offset offset))

(defun reshape-shape (shape size)
  (let ((shape (copy-list (coerce shape 'list))))
    (unless (every (lambda (d) (and (integerp d) (<= -1 d most-positive-fixnum))) shape)
      (error "Invalid reshape dimensions: ~S" shape))
    (let ((inferred (position -1 shape)))
      (when inferred
        (unless (= 1 (count -1 shape)) (error "Only one dimension may be inferred"))
        (let ((known (reduce #'* shape :key (lambda (d) (if (= d -1) 1 d)))))
          (unless (and (plusp known) (zerop (mod size known)))
            (error "Cannot infer reshape dimensions ~S for ~D elements" shape size))
          (setf (nth inferred shape) (/ size known))))
      (unless (= size (reduce #'* shape)) (error "Reshape changes element count")))
    (index-vector shape)))

(defun reshape-strides (tensor shape)
  (when (<= (tensor-size tensor) 1)
    (return-from reshape-strides (row-major-strides shape)))
  (let* ((old (loop for d across (tensor-shape tensor) for s across (tensor-strides tensor)
                    unless (= d 1) collect (cons d s)))
         (new (loop for d across shape for i from 0 unless (= d 1) collect i))
         (strides (make-array (length shape) :element-type 'fixnum :initial-element 0)))
    (loop while (and old new)
          do (let* ((first-old (pop old)) (new-group (list (pop new)))
                    (old-size (car first-old)) (stride (cdr first-old))
                    (new-size (aref shape (first new-group))))
               (loop until (= old-size new-size)
                     do (if (< old-size new-size)
                            (if old
                                (let ((next (pop old)))
                                  (unless (= stride (* (car next) (cdr next)))
                                    (return-from reshape-strides nil))
                                  (setf stride (cdr next) old-size (* old-size (car next))))
                                (return-from reshape-strides nil))
                            (if new
                                (let ((next (pop new)))
                                  (push next new-group)
                                  (setf new-size (* new-size (aref shape next))))
                                (return-from reshape-strides nil))))
               (dolist (axis new-group)
                 (setf (aref strides axis) stride)
                 (setf stride (* stride (aref shape axis))))))
    (when (or old new) (return-from reshape-strides nil))
    (let ((stride 1))
      (loop for axis downfrom (1- (length shape)) to 0
            do (if (= (aref shape axis) 1)
                   (setf (aref strides axis) stride)
                   (setf stride (* (aref shape axis) (aref strides axis))))))
    strides))

(defun reshape (tensor shape &key (copy :auto))
  (check-type tensor tensor)
  (unless (member copy '(:auto :never :always)) (error "Invalid copy policy: ~S" copy))
  (let* ((shape (reshape-shape shape (tensor-size tensor)))
         (strides (unless (eq copy :always) (reshape-strides tensor shape))))
    (cond (strides (layout-view tensor shape strides))
          ((eq copy :never) (error "Reshape requires a copy"))
          (t (layout-view (copy-tensor tensor) shape (row-major-strides shape))))))

(defun transpose (tensor &key (axes nil axes-p))
  (check-type tensor tensor)
  (let* ((rank (tensor-rank tensor))
         (axes (if axes-p
                   (mapcar (lambda (a) (normalize-axis a rank)) (coerce axes 'list))
                   (loop for a downfrom (1- rank) to 0 collect a))))
    (unless (and (= rank (length axes)) (= rank (length (remove-duplicates axes))))
      (error "Transpose requires a permutation of every axis"))
    (layout-view tensor (mapcar (lambda (a) (aref (tensor-shape tensor) a)) axes)
                 (mapcar (lambda (a) (aref (tensor-strides tensor) a)) axes))))

(defun squeeze (tensor &key axis)
  (check-type tensor tensor)
  (let ((axes (if axis (normalize-axes axis (tensor-rank tensor))
                  (loop for d across (tensor-shape tensor) for a from 0 when (= d 1) collect a))))
    (dolist (a axes)
      (unless (= 1 (aref (tensor-shape tensor) a)) (error "Cannot squeeze axis ~D" a)))
    (layout-view tensor
                 (loop for d across (tensor-shape tensor) for a from 0 unless (member a axes) collect d)
                 (loop for s across (tensor-strides tensor) for a from 0 unless (member a axes) collect s))))

(defun expand-dims (tensor &key (axis nil axis-p))
  (check-type tensor tensor)
  (unless axis-p (error "EXPAND-DIMS requires :AXIS"))
  (let ((axis (normalize-axis axis (1+ (tensor-rank tensor))))
        (shape (coerce (tensor-shape tensor) 'list))
        (strides (coerce (tensor-strides tensor) 'list)))
    (layout-view tensor (append (subseq shape 0 axis) (list 1) (subseq shape axis))
                 (append (subseq strides 0 axis) (list 0) (subseq strides axis)))))

(defun slice-range (range size)
  (unless (and (listp range) (<= 2 (length range) 3))
    (error "Invalid slice range: ~S" range))
  (destructuring-bind (start stop &optional (step 1)) range
    (unless (and (integerp step) (not (zerop step))) (error "Slice step must be nonzero"))
    (unless (and (or (null start) (integerp start)) (or (null stop) (integerp stop)))
      (error "Slice bounds must be integers or NIL"))
    (let ((low (if (plusp step) 0 -1)) (high (if (plusp step) size (1- size))))
      (flet ((bound (value default)
               (if (null value) default
                   (cl:max low (cl:min high (if (minusp value) (+ size value) value))))))
        (let* ((start (bound start (if (plusp step) 0 (1- size))))
               (stop (bound stop (if (plusp step) size -1)))
               (count (cl:max 0 (ceiling (- stop start) step))))
          (values start count step))))))

(defun slice (tensor &key selectors)
  (check-type tensor tensor)
  (let ((selectors (coerce selectors 'list)) (shape nil) (strides nil)
        (offset (tensor-offset tensor)))
    (when (> (length selectors) (tensor-rank tensor)) (error "Too many slice selectors"))
    (loop for size across (tensor-shape tensor) for stride across (tensor-strides tensor)
          for axis from 0 for selector = (if (< axis (length selectors)) (nth axis selectors) :all)
          do (cond ((eq selector :all) (push size shape) (push stride strides))
                   ((integerp selector)
                    (let ((index (if (minusp selector) (+ size selector) selector)))
                      (unless (< -1 index size) (error "Slice index ~D is out of bounds" selector))
                      (incf offset (* index stride))))
                   (t (multiple-value-bind (start count step) (slice-range selector size)
                        (push count shape) (push (* step stride) strides)
                        (incf offset (* start stride))))))
    (setf shape (nreverse shape) strides (nreverse strides))
    (layout-view tensor shape strides
                 (if (member 0 shape) (tensor-offset tensor) offset))))

(defun concatenate (tensors &key (axis 0))
  (let ((tensors (coerce tensors 'list)))
    (unless tensors (error "CONCATENATE needs at least one tensor"))
    (mapc (lambda (x) (check-type x tensor)) tensors)
    (let* ((first (first tensors)) (rank (tensor-rank first))
           (axis (normalize-axis axis rank)) (dtype (tensor-dtype first))
           (shape (copy-seq (tensor-shape first))))
      (setf (aref shape axis) 0)
      (dolist (x tensors)
        (unless (and (= rank (tensor-rank x)) (eq dtype (tensor-dtype x))
                     (loop for a below rank always (or (= a axis)
                                                      (= (aref shape a) (aref (tensor-shape x) a)))))
          (error "Concatenation shapes and dtypes must match outside its axis"))
        (incf (aref shape axis) (aref (tensor-shape x) axis)))
      (let ((out (make-tensor shape :dtype dtype)) (start 0))
        (dolist (x tensors out)
          (let ((offset (+ (tensor-offset out) (* start (aref (tensor-strides out) axis)))))
            (call-with-offsets (tensor-shape x) (list (tensor-strides x) (tensor-strides out))
                               (list (tensor-offset x) offset)
                               (lambda (source target)
                                 (setf (storage-ref (tensor-storage out) target)
                                       (storage-ref (tensor-storage x) source)))))
          (incf start (aref (tensor-shape x) axis)))))))

(defun stack (tensors &key (axis 0))
  (let ((tensors (coerce tensors 'list)))
    (unless tensors (error "STACK needs at least one tensor"))
    (mapc (lambda (x) (check-type x tensor)) tensors)
    (let ((shape (tensor-shape (first tensors)))
          (axis (normalize-axis axis (1+ (tensor-rank (first tensors))))))
      (unless (every (lambda (x) (equalp shape (tensor-shape x))) tensors)
        (error "STACK requires identical shapes"))
      (concatenate (mapcar (lambda (x) (expand-dims x :axis axis)) tensors) :axis axis))))

(defun split (tensor sections-or-cuts &key (axis 0))
  (check-type tensor tensor)
  (let* ((axis (normalize-axis axis (tensor-rank tensor)))
         (size (aref (tensor-shape tensor) axis))
         (cuts (if (integerp sections-or-cuts)
                   (progn
                     (unless (and (plusp sections-or-cuts) (zerop (mod size sections-or-cuts)))
                       (error "Split sections must divide axis size evenly"))
                     (loop for i from 1 below sections-or-cuts collect (* i (/ size sections-or-cuts))))
                   (coerce sections-or-cuts 'list))))
    (unless (and (every (lambda (c) (and (integerp c) (<= 0 c size))) cuts)
                 (or (null cuts) (apply #'<= cuts)))
      (error "Split cuts must be ordered and in range"))
    (loop for start = 0 then stop for stop in (append cuts (list size))
          collect (slice tensor :selectors
                         (append (make-list axis :initial-element :all) (list (list start stop)))))))
