(in-package #:cl-tensor/tests)

(in-suite :cl-tensor)

(test filled-constructors
  (dolist (dtype '(:f32 :f64 :c32 :c64 :s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64))
    (let ((zero (ct:zeros '(2 3) :dtype dtype))
          (one (ct:ones '(2 3) :dtype dtype))
          (full (ct:full '(2 3) 7 :dtype dtype)))
      (is (eq dtype (ct:tensor-dtype full)))
      (is (every #'zerop (tensor-values zero)))
      (is (every (lambda (x) (= x 1)) (tensor-values one)))
      (is (every (lambda (x) (= x 7)) (tensor-values full)))))
  (is (= 0 (ct:tref (ct:zeros nil))))
  (is (null (tensor-values (ct:ones '(0 3)))))
  (signals error (ct:full '(0) 1.5 :dtype :s8))
  (signals error (ct:full '(1) 256 :dtype :u8))
  (signals error (ct:full '(1) -1 :dtype :u8))
  (signals error (ct:ones '(1) :dtype :bf16))
  (signals error (ct:full '(1) #c(1 1) :dtype :f32))
  (is (eq :f16 (ct:tensor-dtype (ct:zeros '(2) :dtype :f16)))))

(test from-data
  (let ((tensor (ct:from-data '((1 2 3) (4 5 6)))))
    (is (equalp #(2 3) (ct:tensor-shape tensor)))
    (is (equalp '(1 2 3 4 5 6) (tensor-values tensor))))
  (is (equalp #(2 2) (ct:tensor-shape (ct:from-data #(#(1 2) #(3 4))))))
  (is (equalp #(2 0) (ct:tensor-shape (ct:from-data '(() ())))))
  (is (equalp #(0) (ct:tensor-shape (ct:from-data nil))))
  (is (= 3 (ct:tref (ct:from-data 3))))
  (is (= 4 (ct:tref (ct:from-data (make-array nil :initial-element 4)))))
  (let* ((array (make-array '(2 2) :initial-contents '((1 2) (3 4))))
         (tensor (ct:from-data array :dtype :s16)))
    (setf (aref array 0 0) 99)
    (is (= 1 (ct:tref tensor 0 0))))
  (signals error (ct:from-data '((1 2) (3))))
  (signals error (ct:from-data '(1 (2))))
  (signals error (ct:from-data '(hello)))
  (signals error (ct:from-data "123"))
  (signals error (ct:from-data '(1.5) :dtype :s8))
  (signals error (ct:from-data '(1) :dtype :f16)))

(test sequence-constructors
  (is (equalp '(0 1 2 3) (tensor-values (ct:arange 4))))
  (is (equal '(2 3 4) (tensor-values (ct:arange 2 5 :dtype :s8))))
  (is (equal '(5 3 1) (tensor-values (ct:arange 5 0 -2 :dtype :s8))))
  (is (equalp '(0 1/4 1/2 3/4) (tensor-values (ct:arange 0 1 1/4))))
  (is (null (tensor-values (ct:arange 3 0))))
  (is (null (tensor-values (ct:arange 0 3 -1))))
  (signals error (ct:arange 0 3 0))
  (signals error (ct:arange))
  (signals error (ct:arange 0 1 1 1))
  (signals error (ct:arange 3 :bad t))
  (signals error (ct:arange 0 1 1/2 :dtype :s8))
  (signals error (ct:arange 127 130 :dtype :s8))
  (signals error (ct:arange #c(1 2)))
  (is (= 50 (ct:tensor-size (ct:linspace 0 1))))
  (is (equalp '(0 1/4 1/2 3/4 1) (tensor-values (ct:linspace 0 1 :num 5))))
  (is (equalp '(0 1/4 1/2 3/4) (tensor-values (ct:linspace 0 1 :num 4 :endpoint nil))))
  (is (equalp '(2) (tensor-values (ct:linspace 2 8 :num 1))))
  (is (null (tensor-values (ct:linspace 0 1 :num 0))))
  (is (equal '(3d0 2d0 1d0) (tensor-values (ct:linspace 3 1 :num 3 :dtype :f64))))
  (signals error (ct:linspace 0 1 :dtype :s8))
  (signals error (ct:linspace 0 1 :num -1)))

(test identity-constructor
  (is (equalp '(1 0 0 0 1 0 0 0 1) (tensor-values (ct:eye 3))))
  (is (equal '(0 1 0 0 0 0 1 0) (tensor-values (ct:eye 2 :columns 4 :k 1 :dtype :u8))))
  (is (equalp '(0 0 1 0 0 1) (tensor-values (ct:eye 3 :columns 2 :k -1))))
  (is (every #'zerop (tensor-values (ct:eye 2 :k 4))))
  (is (null (tensor-values (ct:eye 0))))
  (signals error (ct:eye -1))
  (signals error (ct:eye 2 :k 0.5)))

(test access-and-copy
  (let* ((storage (make-array 6 :element-type 'single-float :initial-contents '(0f0 1f0 2f0 3f0 4f0 5f0)))
         (view (ct:make-tensor-view storage '(2 3) :strides '(-3 1) :offset 3))
         (copy (ct:copy-tensor view)))
    (is (equalp '(3 4 5 0 1 2) (tensor-values copy)))
    (is (ct:contiguous-p copy))
    (is (not (eq storage (ct:tensor-storage copy))))
    (is (= 9 (setf (ct:tref view 0 1) 9)))
    (is (= 9f0 (aref storage 4)))
    (is (= 4f0 (ct:tref copy 0 1)))
    (signals error (ct:tref view 0))
    (signals error (ct:tref view -1 0))
    (signals error (setf (ct:tref view 0 0) #c(1 1))))
  (let ((bits (ct:zeros '(2) :dtype :bf16)))
    (setf (ct:tref bits 1) #x3f80)
    (is (= #x3f80 (ct:tref (ct:copy-tensor bits) 1)))
    (signals error (setf (ct:tref bits 0) 1f0)))
  (is (string= "#<TENSOR :F32 NIL>" (princ-to-string (ct:zeros nil))))
  (is (string= "#<TENSOR :F32 (0 3)>" (princ-to-string (ct:zeros '(0 3)))))
  (is (= 1 (ct:tref (ct:copy-tensor (ct:ones nil))))))

(test foreign-access-and-copy
  (dolist (spec '((:f32 :float) (:f64 :double) (:s8 :int8) (:u8 :uint8)
                  (:s16 :int16) (:u16 :uint16) (:s32 :int32) (:u32 :uint32)
                  (:s64 :int64) (:u64 :uint64) (:c32 :float) (:c64 :double)))
    (destructuring-bind (dtype type) spec
      (let* ((complexp (member dtype '(:c32 :c64)))
             (pointer (cffi:foreign-alloc type :count (if complexp 8 4))))
        (unwind-protect
             (let* ((storage (trivial-simd:make-vector-view pointer dtype 4))
                    (tensor (ct:make-tensor-view storage '(2 2)))
                    (value (if complexp #c(3 4) 7)))
               (dotimes (i 2) (dotimes (j 2) (setf (ct:tref tensor i j) value)))
               (is (every (lambda (x) (= x value)) (tensor-values (ct:copy-tensor tensor))))
               (is (= value (ct:tref tensor 1 0))))
          (cffi:foreign-free pointer))))))
