(in-package #:cl-tensor/tests)

(in-suite :cl-tensor)

(test nd-elementwise-dispatch
  (let* ((input (ct:make-tensor-view (ct:tensor-storage (ct:arange 60)) '(3 5)
                                     :strides '(1 6)))
         (other (ct:full '(3 5) 2))
         (mask (ct:compare :gt input 3))
         (calls 0)
         (originals (mapcar (lambda (name) (cons name (symbol-function name)))
                            '(trivial-simd:nd-add! trivial-simd:nd-subtract! trivial-simd:nd-multiply!
                              trivial-simd:nd-divide! trivial-simd:nd-negate! trivial-simd:nd-abs!
                              trivial-simd:nd-sqrt! trivial-simd:nd-reciprocal! trivial-simd:nd-min!
                              trivial-simd:nd-max! trivial-simd:nd-clamp! trivial-simd:nd-compare!
                              trivial-simd:nd-select! trivial-simd:nd-convert!))))
    (unwind-protect
         (progn
           (dolist (entry originals)
             (let ((original (cdr entry)))
               (setf (symbol-function (car entry))
                     (lambda (&rest arguments) (incf calls) (apply original arguments)))))
           (dolist (function (list (lambda () (ct:add input other))
                                  (lambda () (ct:subtract input other))
                                  (lambda () (ct:multiply input other))
                                  (lambda () (ct:divide input other))
                                  (lambda () (ct:negate input))
                                  (lambda () (ct:abs input))
                                  (lambda () (ct:sqrt input))
                                  (lambda () (ct:reciprocal other))
                                  (lambda () (ct:min input other))
                                  (lambda () (ct:max input other))
                                  (lambda () (ct:clamp input 2 8))
                                  (lambda () (ct:compare :lt input other))
                                  (lambda () (ct:select mask input other))
                                  (lambda () (ct:astype input :f64))))
             (setf calls 0)
             (funcall function)
             (is (= 1 calls)))
           (setf calls 0)
           (ct:add (ct:zeros '(0 5)) 2)
           (is (= 1 calls)))
      (dolist (entry originals) (setf (symbol-function (car entry)) (cdr entry))))))

(test arithmetic-and-broadcasting
  (dolist (dtype '(:f32 :f64 :c32 :c64 :s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64))
    (let ((a (ct:from-data '((2) (4)) :dtype dtype))
          (b (ct:from-data '(2 4 8) :dtype dtype)))
      (is (equalp #(2 3) (ct:tensor-shape (ct:add a b))))
      (is (equalp '(4 6 10 6 8 12) (tensor-values (ct:add a b))))
      (is (equalp '(4 8 16 8 16 32) (tensor-values (ct:multiply a b))))
      (is (equalp '(8 6 2) (tensor-values (ct:subtract 10 b))))
      (is (equalp '(4 2 1) (tensor-values (ct:divide 8 b))))
      (is (equalp '(3 5 9) (tensor-values (ct:add b 1))))
      (let ((out (ct:zeros '(2 3) :dtype dtype)))
        (is (eq out (ct:add! out a b)))
        (is (equalp '(4 6 10 6 8 12) (tensor-values out))))))
  (is (= 5 (ct:tref (ct:add (ct:from-data 3) 2))))
  (let ((out (ct:zeros nil :dtype :s8)))
    (is (eq out (ct:add! out 2 3)))
    (is (= 5 (ct:tref out))))
  (is (equalp #(0 3) (ct:tensor-shape (ct:add (ct:zeros '(0 3)) (ct:ones '(1 3))))))
  (signals error (ct:add 1 2))
  (signals error (ct:add (ct:ones '(2 3)) (ct:ones '(2))))
  (signals error (ct:add (ct:zeros '(0 3)) (ct:ones '(2 3)))))

(test integer-semantics
  (is (= -128 (ct:tref (ct:add (ct:from-data 127 :dtype :s8) 1))))
  (is (= 4 (ct:tref (ct:add (ct:from-data 250 :dtype :u8) 10))))
  (is (= -2 (ct:tref (ct:divide (ct:from-data -7 :dtype :s8) 3))))
  (is (= -128 (ct:tref (ct:divide (ct:from-data -128 :dtype :s8) -1))))
  (is (= -128 (ct:tref (ct:abs (ct:from-data -128 :dtype :s8)))))
  (signals division-by-zero (ct:divide (ct:ones '(1) :dtype :s8) 0))
  (signals error (ct:add (ct:ones '(0) :dtype :s8) 1f0))
  (signals error (ct:add (ct:ones '(1) :dtype :u8) 256)))

(test unary-and-bounded-operations
  (let ((x (ct:from-data '(1 4 16))))
    (is (equalp '(-1 -4 -16) (tensor-values (ct:negate x))))
    (is (equalp '(1 2 4) (tensor-values (ct:sqrt x))))
    (is (equalp '(1 1/4 1/16) (tensor-values (ct:reciprocal x))))
    (is (equalp '(1 4 8) (tensor-values (ct:min x 8))))
    (is (equalp '(2 4 16) (tensor-values (ct:max 2 x))))
    (is (equalp '(2 4 8) (tensor-values (ct:clamp x 2 8))))
    (let ((out (ct:zeros '(3))))
      (is (eq out (ct:sqrt! out x)))
      (is (equalp '(1 2 4) (tensor-values out)))))
  (is (equalp '(1 2) (tensor-values (ct:abs (ct:from-data '(-1 2))))))
  (let* ((x (ct:from-data '(#c(3 4) #c(5 12)) :dtype :c64))
         (magnitude (ct:abs x)))
    (is (eq :f64 (ct:tensor-dtype magnitude)))
    (is (equal '(5d0 13d0) (tensor-values magnitude)))
    (is (equalp '(#c(-3 -4) #c(-5 -12)) (tensor-values (ct:negate x))))
    (is (= #c(2d0 1d0) (ct:tref (ct:sqrt (ct:from-data #c(3 4) :dtype :c64))))))
  (signals error (ct:sqrt (ct:zeros '(0) :dtype :s8)))
  (signals error (ct:reciprocal (ct:zeros '(0) :dtype :u8)))
  (signals error (ct:min (ct:zeros '(0) :dtype :c32) 1))
  (signals error (ct:clamp (ct:ones '(1)) 2 1))
  (signals error (ct:clamp (ct:zeros '(0)) 2 1)))

(test comparison-and-selection
  (let* ((x (ct:from-data '((1 2 3) (4 5 6))))
         (mask (ct:compare :gt x 3)))
    (is (eq :u8 (ct:tensor-dtype mask)))
    (is (equal '(0 0 0 1 1 1) (tensor-values mask)))
    (is (equalp '(0 0 0 4 5 6) (tensor-values (ct:select mask x 0))))
    (is (equal '(2 2 2 1 1 1) (tensor-values (ct:select mask 1 2 :dtype :s8))))
    (let ((out (ct:zeros '(2 3))))
      (is (eq out (ct:select! out mask x 0)))))
  (dolist (spec '((:eq (0 1 0)) (:ne (1 0 1)) (:lt (1 0 0))
                  (:le (1 1 0)) (:gt (0 0 1)) (:ge (0 1 1))))
    (is (equal (second spec) (tensor-values (ct:compare (first spec) (ct:arange 3) 1)))))
  (is (equalp '(3 0) (tensor-values (ct:select (ct:from-data '(2 0) :dtype :u8)
                                             (ct:from-data '(3 4)) 0))))
  (is (equal '(1 0) (tensor-values (ct:compare :eq
                                            (ct:from-data '(#c(1 2) #c(2 3)) :dtype :c32)
                                            #c(1 2)))))
  (signals error (ct:compare :lt (ct:zeros '(0) :dtype :c32) 1))
  (signals error (ct:compare :bad (ct:zeros '(0)) 1))
  (signals error (ct:select (ct:zeros '(0)) 1 0 :dtype :f32))
  (signals error (ct:select (ct:zeros '(0) :dtype :u8) 1 0))
  (signals error (ct:select (ct:zeros '(0) :dtype :u8) (ct:zeros '(0)) 0 :dtype nil))
  (signals error (ct:select (ct:ones '(1) :dtype :u8) (ct:ones '(1)) 0 :dtype :f64)))

(test dtype-and-output-validation
  (signals type-error (ct:add! nil (ct:ones nil) 1))
  (signals type-error (ct:compare! nil :eq (ct:ones nil) 1))
  (signals type-error (ct:select! nil (ct:zeros nil :dtype :u8) 1 0))
  (let ((out (ct:full '(2) 9)))
    (signals error (ct:add! out (ct:ones '(3)) 1))
    (is (equalp '(9 9) (tensor-values out)))
    (signals error (ct:add! out (ct:ones '(2) :dtype :f64) 1))
    (is (equalp '(9 9) (tensor-values out))))
  (signals error (ct:add (ct:zeros '(0)) (ct:zeros '(0) :dtype :f64)))
  (signals error (ct:add (ct:zeros '(0) :dtype :bf16) 1))
  (signals error (ct:abs! (ct:zeros '(0) :dtype :c32) (ct:zeros '(0) :dtype :c32)))
  (signals error (ct:compare! (ct:zeros '(0)) :eq (ct:zeros '(0)) 0)))

(test strided-output-and-aliases
  (let* ((base (ct:arange 6))
         (storage (ct:tensor-storage base))
         (transpose (ct:make-tensor-view storage '(3 2) :strides '(1 3)))
         (out-storage (make-array 6 :element-type 'single-float :initial-element 0f0))
         (out (ct:make-tensor-view out-storage '(3 2) :strides '(-1 3) :offset 2)))
    (ct:add! out transpose 10)
    (is (equalp '(10 13 11 14 12 15) (tensor-values out))))
  (let* ((base (ct:arange 9))
         (storage (ct:tensor-storage base))
         (input (ct:make-tensor-view storage '(2 3)))
         (out (ct:make-tensor-view storage '(2 3) :offset 3)))
    (ct:add! out input 10)
    (is (equalp '(10 11 12 13 14 15) (tensor-values out))))
  (let* ((base (ct:arange 9))
         (storage (ct:tensor-storage base))
         (out (ct:make-tensor-view storage '(3 3)))
         (transpose (ct:make-tensor-view storage '(3 3) :strides '(1 3))))
    (ct:add! out transpose 10)
    (is (equalp '(10 13 16 11 14 17 12 15 18) (tensor-values out))))
  (let* ((base (ct:arange 6))
         (out (ct:make-tensor-view (ct:tensor-storage base) '(2 3)))
         (row (ct:make-tensor-view (ct:tensor-storage base) '(1 3))))
    (ct:add! out out row)
    (is (equalp '(0 2 4 3 5 7) (tensor-values out))))
  (let* ((storage (ct:tensor-storage (ct:zeros '(6))))
         (out (ct:make-tensor-view storage '(2 3) :strides '(0 1))))
    (signals error (ct:add! out (ct:ones '(2 3)) 1))
    (is (every #'zerop storage)))
  (let* ((storage (ct:tensor-storage (ct:zeros '(9))))
         (out (ct:make-tensor-view storage '(2 3) :strides '(2 3))))
    (ct:add! out (ct:ones '(2 3)) 1)
    (is (every (lambda (x) (= 2 x)) (tensor-values out))))
  (let ((a (ct:from-data '((2) (3))))
        (b (ct:from-data '(4 5 6))))
    (is (equalp '(6 7 8 7 8 9) (tensor-values (ct:add a b)))))
  (let* ((storage (ct:tensor-storage (ct:from-data '(4))))
         (broadcast (ct:make-tensor-view storage '(2 3) :strides '(0 0))))
    (is (equalp '(2 2 2 2 2 2) (tensor-values (ct:sqrt broadcast))))))

(test explicit-conversion
  (is (equal '(0 2 2 4) (tensor-values (ct:astype (ct:from-data '(0.5 1.5 2.5 3.5)) :s8))))
  (is (equal '(0 1 2 3) (tensor-values (ct:astype (ct:from-data '(0.5 1.5 2.5 3.5)) :s8 :rounding :truncate))))
  (is (equal '(-2 1) (tensor-values (ct:astype (ct:from-data '(-1.5 1.5)) :s8 :rounding :floor))))
  (is (equal '(-1 2) (tensor-values (ct:astype (ct:from-data '(-1.5 1.5)) :s8 :rounding :ceiling))))
  (is (equal '(0 255) (tensor-values (ct:astype (ct:from-data '(-100 1000) :dtype :s16) :u8))))
  (is (= #c(3d0 0d0) (ct:tref (ct:astype (ct:from-data 3) :c64))))
  (is (= 3d0 (ct:tref (ct:astype (ct:from-data #c(3 0) :dtype :c32) :f64))))
  (signals error (ct:astype (ct:from-data #c(3 1) :dtype :c32) :f32))
  (signals error (ct:astype (ct:zeros '(0)) :s8 :rounding :bad))
  (signals error (ct:astype (ct:zeros '(0) :dtype :u16) :bf16))
  (let* ((x (ct:ones '(2))) (copy (ct:astype x :f32)))
    (is (not (eq (ct:tensor-storage x) (ct:tensor-storage copy)))))
  (dolist (dtype '(:f16 :bf16))
    (let* ((x (ct:from-data '(0 1 -2 0.5) :dtype :f64))
           (encoded (ct:astype x dtype))
           (decoded (ct:astype encoded :f64)))
      (is (eq dtype (ct:tensor-dtype encoded)))
      (is (equal '(0d0 1d0 -2d0 0.5d0) (tensor-values decoded)))
      (is (equal (tensor-values encoded) (tensor-values (ct:astype encoded dtype))))))
  (dolist (dtype '(:f16 :bf16))
    (let ((bits (ct:make-tensor-view
                 (make-array 5 :element-type '(unsigned-byte 16)
                               :initial-contents '(#x8000 #x7fff #xffff #x0001 #x7e01))
                 '(5) :dtype dtype)))
      (is (equal '(#x8000 #x7fff #xffff #x0001 #x7e01) (tensor-values (ct:astype bits dtype))))))
  (let* ((x (ct:arange 6))
         (view (ct:make-tensor-view (ct:tensor-storage x) '(3 2) :strides '(1 3))))
    (is (equal '(0d0 3d0 1d0 4d0 2d0 5d0) (tensor-values (ct:astype view :f64))))))

(test remaining-out-forms
  (let ((x (ct:from-data '(1 4 16))) (out (ct:zeros '(3))))
    (dolist (spec (list (list #'ct:negate! '(-1 -4 -16)) (list #'ct:abs! '(1 4 16))
                        (list #'ct:reciprocal! '(1 1/4 1/16))))
      (is (eq out (funcall (first spec) out x)))
      (is (equalp (second spec) (tensor-values out))))
    (is (eq out (ct:clamp! out x 2 8)))
    (is (equalp '(2 4 8) (tensor-values out)))
    (let ((mask (ct:zeros '(3) :dtype :u8)))
      (is (eq mask (ct:compare! mask :gt x 3)))
      (is (equal '(0 1 1) (tensor-values mask)))))
  (let ((out (ct:zeros nil)))
    (ct:negate! out 3)
    (is (= -3f0 (ct:tref out))))
  (let ((out (ct:zeros nil :dtype :u8)))
    (ct:compare! out :lt 2 3)
    (is (= 1 (ct:tref out))))
  (let* ((storage (ct:tensor-storage (ct:from-data '(2) :dtype :u8)))
         (mask (ct:make-tensor-view storage '(2 3) :strides '(0 0))))
    (is (equalp '(5 5 5 5 5 5) (tensor-values (ct:select mask 5 0 :dtype :f32)))))
  (let ((x (ct:zeros '(0 2))))
    (dolist (function (list #'ct:negate #'ct:abs #'ct:sqrt #'ct:reciprocal))
      (is (= 0 (ct:tensor-size (funcall function x)))))
    (is (= 0 (ct:tensor-size (ct:clamp x 0 1))))
    (is (= 0 (ct:tensor-size (ct:select (ct:compare :eq x 0) x 0))))))

(test all-computational-conversions
  (dolist (source '(:f32 :f64 :c32 :c64 :s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64))
    (dolist (destination '(:f32 :f64 :c32 :c64 :s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64))
      (let ((result (ct:astype (ct:full '(2 2) 3 :dtype source) destination)))
        (is (eq destination (ct:tensor-dtype result)))
        (is (every (lambda (x) (= x 3)) (tensor-values result)))))))

(test unary-and-select-dtype-coverage
  (dolist (dtype '(:f32 :f64 :c32 :c64 :s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64))
    (let* ((x (ct:full '(2 2) 4 :dtype dtype))
           (type (ct:dtype-element-type dtype))
           (negative (if (and (listp type) (eq (first type) 'unsigned-byte))
                         (- (expt 2 (second type)) 4) -4)))
      (is (every (lambda (v) (= v negative)) (tensor-values (ct:negate x))))
      (is (every (lambda (v) (= v 4)) (tensor-values (ct:abs x))))
      (when (member dtype '(:f32 :f64 :c32 :c64))
        (is (every (lambda (v) (= v 2)) (tensor-values (ct:sqrt x))))
        (is (every (lambda (v) (= v 1/4)) (tensor-values (ct:reciprocal x)))))
      (unless (member dtype '(:c32 :c64))
        (is (every (lambda (v) (= v 3)) (tensor-values (ct:min x 3))))
        (is (every (lambda (v) (= v 5)) (tensor-values (ct:max x 5))))
        (is (every (lambda (v) (= v 3)) (tensor-values (ct:clamp x 1 3)))))
      (let* ((mask (ct:from-data '((0 1) (2 0)) :dtype :u8))
             (out (ct:zeros '(2 2) :dtype dtype)))
        (is (equalp '(0 4 4 0) (tensor-values (ct:select mask x 0))))
        (is (eq out (ct:select! out mask x 0)))
        (is (equalp '(0 4 4 0) (tensor-values out)))))))

(test foreign-bulk-and-overlap
  (let ((pointer (cffi:foreign-alloc :float :count 12)))
    (unwind-protect
         (let* ((storage (trivial-simd:make-vector-view pointer :f32 12))
                (all (ct:make-tensor-view storage '(12)))
                (input (ct:make-tensor-view storage '(2 3)))
                (shifted-storage (trivial-simd:make-vector-view pointer :f32 9 :offset 3))
                (out (ct:make-tensor-view shifted-storage '(2 3))))
           (dotimes (i 12) (setf (ct:tref all i) (+ i 1)))
           (ct:add! out input 10)
           (is (equalp '(11 12 13 14 15 16) (tensor-values out)))
           (is (equal '(11d0 12d0 13d0 14d0 15d0 16d0) (tensor-values (ct:astype out :f64))))
           (let ((reverse (ct:make-tensor-view shifted-storage '(2 3) :strides '(-3 -1) :offset 5)))
             (is (equalp '(17 16 15 14 13 12) (tensor-values (ct:add reverse 1)))))
           (ct:multiply! out out 2)
           (is (equalp '(22 24 26 28 30 32) (tensor-values out)))
           (dotimes (i 12) (setf (ct:tref all i) (+ i 1)))
           (let* ((bytes (trivial-simd:make-vector-view pointer :u8 48))
                  (mask (ct:make-tensor-view bytes '(2 3) :offset 12)))
             (ct:compare! mask :lt input 4)
             (is (equal '(1 1 1 0 0 0) (tensor-values mask))))
           (let* ((bytes (trivial-simd:make-vector-view pointer :u8 48))
                  (mask (ct:make-tensor-view bytes '(2 3))))
             (loop for value in '(0 1 0 1 0 1) for i from 0
                   do (setf (ct:tref mask (floor i 3) (mod i 3)) value))
             (ct:select! input mask (ct:full '(2 3) 7) 0)
             (is (equalp '(0 7 0 7 0 7) (tensor-values input)))))
      (cffi:foreign-free pointer))))

(test mixed-storage-alias
  (let ((storage (ct:tensor-storage (ct:arange 9))))
    (cffi:with-pointer-to-vector-data (pointer storage)
      (let* ((foreign (trivial-simd:make-vector-view pointer :f32 9))
             (input (ct:make-tensor-view foreign '(2 3)))
             (out (ct:make-tensor-view storage '(2 3) :offset 3)))
        (ct:add! out input 10)
        (is (equalp '(10 11 12 13 14 15) (tensor-values out)))))))

(test strided-complex-output
  (let* ((x (ct:from-data '((#c(3 4) #c(5 12)) (#c(0 2) #c(8 15))) :dtype :c64))
         (storage (ct:tensor-storage (ct:zeros '(4) :dtype :f64)))
         (out (ct:make-tensor-view storage '(2 2) :strides '(1 2))))
    (is (eq out (ct:abs! out x)))
    (is (equal '(5d0 13d0 2d0 17d0) (tensor-values out)))))

(test foreign-overlap-across-staging-blocks
  (let ((pointer (cffi:foreign-alloc :float :count 15000)))
    (unwind-protect
         (let* ((storage (trivial-simd:make-vector-view pointer :f32 15000))
                (all (ct:make-tensor-view storage '(15000)))
                (input (ct:make-tensor-view storage '(2 5000)))
                (out (ct:make-tensor-view storage '(2 5000) :offset 5000)))
           (dotimes (i 15000) (setf (ct:tref all i) i))
           (ct:add! out input 1)
           (is (loop for value in (tensor-values out) for expected from 1 always (= value expected))))
      (cffi:foreign-free pointer))))
