(in-package #:cl-tensor/tests)

(in-suite :cl-tensor)

(defun reference-matmul (a b)
  (let* ((as (coerce (ct:tensor-shape a) 'list))
         (bs (coerce (ct:tensor-shape b) 'list))
         (av (= (length as) 1)) (bv (= (length bs) 1))
         (ab (unless av (butlast as 2))) (bb (unless bv (butlast bs 2)))
         (rank (max (length ab) (length bb)))
         (batch (loop for axis from rank downto 1
                      for ad = (if (< (length ab) axis) 1 (nth (- (length ab) axis) ab))
                      for bd = (if (< (length bb) axis) 1 (nth (- (length bb) axis) bb))
                      collect (if (= ad 1) bd ad)))
         (m (if av 1 (nth (- (length as) 2) as)))
         (n (if bv 1 (car (last bs))))
         (k (car (last as)))
         (shape (append batch (unless av (list m)) (unless bv (list n)))))
    (labels ((local-batch (dimensions indices)
               (mapcar (lambda (dimension index) (if (= dimension 1) 0 index))
                       dimensions (nthcdr (- rank (length dimensions)) indices))))
      (values shape
              (loop for indices in (all-indices shape)
                    for batches = (subseq indices 0 rank)
                    for row = (if av 0 (nth rank indices))
                    for col = (if bv 0 (car (last indices)))
                    collect (loop for inner below k
                                  sum (* (apply #'ct:tref a
                                                (if av (list inner)
                                                    (append (local-batch ab batches) (list row inner))))
                                         (apply #'ct:tref b
                                                (if bv (list inner)
                                                    (append (local-batch bb batches) (list inner col)))))))))))

(defun check-matmul (a b &optional out)
  (multiple-value-bind (shape expected) (reference-matmul a b)
    (let* ((result (if out (ct:matmul! out a b) (ct:matmul a b)))
           (tolerance (if (eq (ct:tensor-dtype a) :f32) 1d-5 1d-12)))
      (is (equalp shape (coerce (ct:tensor-shape result) 'list)))
      (is (eq (ct:tensor-dtype a) (ct:tensor-dtype result)))
      (when out (is (eq out result)))
      (loop for value in (tensor-values result) for reference in expected
            do (is (<= (abs (- value reference)) (* tolerance (max 1 (abs reference)))))))))

(test matmul-values-and-shapes
  (dolist (dtype '(:f32 :f64))
    (let ((matrix (ct:from-data '((1 2 3) (4 5 6)) :dtype dtype))
          (right (ct:from-data '((2 3) (4 5) (6 7)) :dtype dtype))
          (vector (ct:from-data '(2 3 4) :dtype dtype)))
      (is (equalp '(28 34 64 79) (tensor-values (ct:matmul matrix right))))
      (is (equalp '(20 47) (tensor-values (ct:matmul matrix vector))))
      (is (equalp '(40 49) (tensor-values (ct:matmul vector right))))
      (is (= 29 (ct:tref (ct:matmul vector vector))))
      (is (equalp #() (ct:tensor-shape (ct:matmul vector vector))))
      (check-matmul matrix right)
      (check-matmul matrix vector)
      (check-matmul vector right)
      (check-matmul vector vector (ct:zeros '() :dtype dtype))
      (let ((result (ct:matmul matrix right)))
        (is (ct:contiguous-p result))
        (is (not (eq (ct:tensor-storage matrix) (ct:tensor-storage result))))
        (is (not (eq (ct:tensor-storage right) (ct:tensor-storage result))))))
    (dolist (shapes '(((2 1 3 4) (1 5 4 2)) ((3 4) (2 4 5))
                      ((2 3 4) (4)) ((4) (2 4 3)) ((1) (1 1))
                      ((1 1) (1)) ((1 1 1) (1 1 1))))
      (check-matmul (ct:ones (first shapes) :dtype dtype)
                    (ct:ones (second shapes) :dtype dtype)))))

(test matmul-empty-and-validation
  (dolist (dtype '(:f32 :f64))
    (dolist (shapes '(((0) (0)) ((2 0) (0 3)) ((0 2) (2 3))
                      ((2 3) (3 0)) ((0 2 3) (1 3 4)) ((2 0) (0))
                      ((0) (3 0 2)) ((2 1 3 0) (1 4 0 2))))
      (check-matmul (ct:zeros (first shapes) :dtype dtype)
                    (ct:zeros (second shapes) :dtype dtype)))
    (let ((empty (ct:make-tensor-view (ct:tensor-storage (ct:zeros '(0) :dtype dtype))
                                     '(2 0) :offset 99 :strides '(17 -3)))
          (out (ct:full '(3 2) 7 :dtype dtype)))
      (check-matmul empty (ct:zeros '(0 3) :dtype dtype) (ct:transpose out))
      (is (every #'zerop (tensor-values out))))
    (let ((out (ct:full '(2 2) 7 :dtype dtype)))
      (signals error (ct:matmul! out (ct:ones '(2 3) :dtype dtype) (ct:ones '(4 2) :dtype dtype)))
      (signals error (ct:matmul! out (ct:ones '(2 3) :dtype dtype) (ct:ones '(3 3) :dtype dtype)))
      (is (equalp '(7 7 7 7) (tensor-values out)))))
  (signals error (ct:matmul 1 (ct:ones '(1))))
  (signals error (ct:matmul (ct:from-data 1) (ct:ones '(1))))
  (signals error (ct:matmul (ct:ones '(1)) (ct:from-data 1)))
  (signals error (ct:matmul! nil (ct:ones '(1)) (ct:ones '(1))))
  (signals error (ct:matmul (ct:ones '(0 2 3)) (ct:ones '(2 4))))
  (signals error (ct:matmul (ct:ones '(2 3 4)) (ct:ones '(3 4 2))))
  (signals error (ct:matmul (ct:ones '(1)) (ct:ones '(1) :dtype :f64)))
  (signals error (ct:matmul! (ct:zeros '(0 2) :dtype :f64) (ct:zeros '(0 3)) (ct:zeros '(3 2))))
  (dolist (dtype '(:c32 :c64 :s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64 :f16 :bf16))
    (signals error (ct:matmul (ct:zeros '(0) :dtype dtype) (ct:zeros '(0) :dtype dtype))))
  (let* ((storage (ct:tensor-storage (ct:full '(10) 7)))
         (bad (ct:make-tensor-view storage '(2 2) :strides '(1 1))))
    (signals error (ct:matmul! bad (ct:ones '(2 2)) (ct:ones '(2 2))))
    (is (every (lambda (value) (= 7 value)) storage)))
  (signals error (ct:matmul (ct:make-tensor-view (ct:tensor-storage (ct:zeros '(0)))
                                               '(0 1073741824))
                           (ct:zeros '(1)))))

(test matmul-layouts-and-transpose-adapter
  (dolist (dtype '(:f32 :f64))
    (let* ((storage (ct:tensor-storage (ct:arange 40 :dtype dtype)))
           (padded (ct:make-tensor-view storage '(3 4) :strides '(7 1) :offset 2))
           (transposed (ct:transpose padded))
           (reversed (ct:slice padded :selectors '((nil nil -1) (nil nil -1))))
           (broadcast (ct:make-tensor-view storage '(3 4) :strides '(0 0) :offset 2))
           (irregular (ct:make-tensor-view storage '(3 4) :strides '(2 5) :offset 1)))
      (multiple-value-bind (adapter transpose) (cl-tensor::matmul-matrix-adapter transposed)
        (let ((view (funcall adapter 2)))
          (is (eq :transpose transpose))
          (is (eq storage (trivial-simd/blas:matrix-view-data view)))
          (is (= 7 (trivial-simd/blas:matrix-view-leading-dimension view)))
          (is (= 2 (trivial-simd/blas:matrix-view-offset view)))))
      (dolist (a (list padded transposed reversed broadcast irregular))
        (let* ((k (aref (ct:tensor-shape a) 1))
               (b (ct:reshape (ct:arange (* k 2) :dtype dtype) (list k 2))))
          (check-matmul a b)
          (check-matmul a (ct:transpose (ct:copy-tensor (ct:transpose b))))
          (check-matmul a (ct:ones (list k) :dtype dtype))
          (check-matmul (ct:ones (list (aref (ct:tensor-shape a) 0)) :dtype dtype) a))))
    (let* ((storage (ct:tensor-storage (ct:arange 40 :dtype dtype)))
           (vector (ct:make-tensor-view storage '(4) :strides '(-3) :offset 12))
           (broadcast (ct:make-tensor-view storage '(4) :strides '(0) :offset 2))
           (matrix (ct:reshape (ct:arange 12 :dtype dtype) '(3 4))))
      (dolist (v (list vector broadcast))
        (check-matmul v vector)
        (check-matmul matrix v)
        (check-matmul v (ct:transpose matrix))))
    (let* ((storage (ct:tensor-storage (ct:zeros '(20) :dtype dtype)))
           (a (ct:from-data '((1 2) (3 4)) :dtype dtype))
           (b (ct:from-data '((5 6) (7 8)) :dtype dtype)))
      (dolist (layout '((5 1 2) (1 5 2) (-5 -2 12) (3 2 1)))
        (check-matmul a b (ct:make-tensor-view storage '(2 2)
                                              :strides (subseq layout 0 2) :offset (third layout))))
      (let ((out (ct:make-tensor-view storage '(2) :strides '(-3) :offset 4)))
        (check-matmul a (ct:ones '(2) :dtype dtype) out)
        (check-matmul (ct:ones '(2) :dtype dtype) b out)))
    (let* ((storage (ct:tensor-storage (ct:ones '(1) :dtype dtype)))
           (a (ct:make-tensor-view storage '(1 1) :strides '(-99 0))))
      (check-matmul a a)
      (check-matmul a (ct:ones '(1) :dtype dtype)
                    (ct:make-tensor-view storage '(1) :strides '(0))))))

(test matmul-aliases-across-batches
  (dolist (dtype '(:f32 :f64))
    (let ((a (ct:from-data '((1 2) (3 4)) :dtype dtype))
          (b (ct:from-data '((5 6) (7 8)) :dtype dtype)))
      (check-matmul a b a)
      (check-matmul a b b)
      (check-matmul a a (ct:transpose a)))
    (let* ((a (ct:reshape (ct:arange 8 :dtype dtype) '(2 2 2)))
           (out (ct:slice a :selectors '((nil nil -1) :all :all))))
      (check-matmul a (ct:full '(2 2) 2 :dtype dtype) out))
    (let* ((storage (ct:tensor-storage (ct:arange 12 :dtype dtype)))
           (a (ct:make-tensor-view storage '(2 2) :offset 4))
           (out (ct:make-tensor-view storage '(3 2 2))))
      (check-matmul a (ct:ones '(3 2 2) :dtype dtype) out))))

(test matmul-fractional-products
  (dolist (dtype '(:f32 :f64))
    (flet ((fractional-tensor (shape)
             (let ((tensor (ct:zeros shape :dtype dtype)))
               (dotimes (i (ct:tensor-size tensor))
                 (setf (aref (ct:tensor-storage tensor) i)
                       (coerce (/ (- (mod (* i 7) 17) 8) 11) (ct:dtype-element-type dtype))))
               tensor)))
      (let ((a (fractional-tensor '(12 17))) (b (fractional-tensor '(17 9))))
        (check-matmul a b)
        (check-matmul (ct:transpose (ct:copy-tensor (ct:transpose a)))
                      (ct:transpose (ct:copy-tensor (ct:transpose b)))
                      (ct:transpose (ct:full '(9 12) 7 :dtype dtype))))
      (let ((a (fractional-tensor '(33 33))) (v (fractional-tensor '(33))))
        (check-matmul a v)
        (check-matmul v (ct:transpose a))
        (check-matmul v v)))))

(test matmul-foreign-and-mixed-storage
  (dolist (dtype '(:f32 :f64))
    (cffi:with-foreign-object (pointer (if (eq dtype :f32) :float :double) 32)
      (let* ((storage (trivial-simd:make-vector-view pointer dtype 32))
             (other (trivial-simd:make-vector-view (cffi:inc-pointer pointer (* 4 (ct:dtype-bytes dtype)))
                                                  dtype 24))
             (a (ct:make-tensor-view storage '(2 2 2)))
             (b (ct:from-data '((1 2) (3 4)) :dtype dtype))
             (out (ct:make-tensor-view other '(2 2 2))))
        (dotimes (i 32) (setf (cl-tensor::storage-ref storage i) (cl-tensor::coerce-value (mod i 7) dtype)))
        (check-matmul a b)
        (check-matmul b a)
        (check-matmul a b out)
        (check-matmul a out (ct:zeros '(2 2 2) :dtype dtype))
        (check-matmul (ct:slice a :selectors '(0 :all :all))
                      (ct:ones '(2) :dtype dtype)
                      (ct:make-tensor-view other '(2) :strides '(-2) :offset 12))
        (let ((vector (ct:make-tensor-view storage '(2) :strides '(-2) :offset 4)))
          (check-matmul vector vector (ct:make-tensor-view other '() :offset 2)))))))

(test random-matmul-matches-enumeration
  (let ((*state* #+sbcl (sb-ext:seed-random-state 808) #-sbcl (make-random-state t)))
    (dotimes (trial 250)
      (let* ((m (random-between 0 4)) (k (random-between 0 4)) (n (random-between 0 4))
             (batch (loop repeat (random-between 0 2) collect (random-between 0 3)))
             (left-vector (zerop (random-between 0 3)))
             (right-vector (zerop (random-between 0 3)))
             (a-shape (if left-vector (list k)
                          (append (loop for dimension in batch
                                        collect (if (zerop (random-between 0 1)) 1 dimension)) (list m k))))
             (b-shape (if right-vector (list k)
                          (append (nthcdr (random-between 0 (length batch)) batch) (list k n))))
             (dtype (if (evenp trial) :f32 :f64))
             (a (random-data-view a-shape)) (b (random-data-view b-shape)))
        (when (eq dtype :f64)
          (flet ((double-view (tensor)
                   (ct:make-tensor-view
                    (map '(simple-array double-float (*)) (lambda (value) (float value 1d0))
                         (ct:tensor-storage tensor))
                    (ct:tensor-shape tensor) :strides (ct:tensor-strides tensor)
                    :offset (ct:tensor-offset tensor))))
            (setf a (double-view a) b (double-view b))))
        (multiple-value-bind (shape expected) (reference-matmul a b)
          (declare (ignore expected))
          (let ((out (random-output-view shape)))
            (when (eq dtype :f64)
              (setf out (ct:make-tensor-view
                         (make-array (length (ct:tensor-storage out)) :element-type 'double-float
                                                                      :initial-element 0d0)
                         shape :strides (ct:tensor-strides out) :offset (ct:tensor-offset out))))
            (check-matmul a b)
            (check-matmul a b out)))))))
