(in-package #:cl-tensor/tests)

(in-suite :cl-tensor)

(defun normalization-reference (operation input axes &key weights (epsilon 1e-6))
  (let* ((shape (coerce (ct:tensor-shape input) 'list))
         (indices (all-indices shape))
         (kept (loop for a below (length shape) unless (member a axes) collect a)))
    (loop for index in indices
          for x = (float (apply #'ct:tref input index) 1d0)
          for group = (loop for candidate in indices
                            when (loop for a in kept always (= (nth a index) (nth a candidate)))
                              collect (float (apply #'ct:tref input candidate) 1d0))
          for weight = (cond ((null weights) 1d0)
                             ((ct:tensorp weights)
                              (let* ((wshape (coerce (ct:tensor-shape weights) 'list))
                                     (tail (nthcdr (- (length shape) (length wshape)) index)))
                                (apply #'ct:tref weights
                                       (loop for d in wshape for i in tail collect (if (= d 1) 0 i)))))
                             (t weights))
          collect (ecase operation
                    (:softmax
                     (let ((maximum (reduce #'max group)))
                       (/ (exp (- x maximum)) (loop for v in group sum (exp (- v maximum))))))
                    (:rmsnorm
                     (* weight (/ x (sqrt (+ epsilon (/ (loop for v in group sum (* v v))
                                                       (length group)))))))))))

(defun check-normalization-reference (operation input axis axes &key weights (epsilon 1e-6) accumulate)
  (let* ((function (ecase operation (:softmax #'ct:softmax) (:rmsnorm #'ct:rmsnorm)))
         (keywords (append (list :axis axis :accumulate accumulate)
                           (when (eq operation :rmsnorm) (list :weights weights :epsilon epsilon))))
         (result (apply function input keywords))
         (reference (normalization-reference operation input axes :weights weights :epsilon epsilon))
         (tolerance (if (eq (ct:tensor-dtype input) :f32) 1d-5 1d-12)))
    (is (equalp (ct:tensor-shape input) (ct:tensor-shape result)))
    (is (eq (ct:tensor-dtype input) (ct:tensor-dtype result)))
    (is (ct:contiguous-p result))
    (is (not (eq (ct:tensor-storage result) (ct:tensor-storage input))))
    (is (= (ct:tensor-size input) (length reference)))
    (loop for actual in (tensor-values result) for expected in reference
          do (is (<= (abs (- actual expected)) (* tolerance (+ 1d0 (abs expected))))))
    t))

(test normalization-values-and-axes
  (dolist (dtype '(:f32 :f64))
    (let* ((a (ct:reshape (ct:arange 24 :dtype dtype) '(2 3 4)))
           (weights (ct:from-data '(1 2 3 4) :dtype dtype)))
      (dolist (pair '((-1 (2)) (0 (0)) (nil (0 1 2)) ((2 0) (0 2)) (#(1 2) (1 2)) (#() nil)))
        (destructuring-bind (axis axes) pair
          (dolist (accumulate '(nil :f64))
            (check-normalization-reference :softmax a axis axes :accumulate accumulate)
            (check-normalization-reference :rmsnorm a axis axes :weights weights :accumulate accumulate)
            (check-normalization-reference :rmsnorm a axis axes :weights 2 :epsilon 0.1
                                           :accumulate accumulate))))
      (is (equalp (tensor-values (ct:softmax a)) (tensor-values (ct:softmax a :axis -1))))
      (is (equalp (tensor-values (ct:rmsnorm a)) (tensor-values (ct:rmsnorm a :axis -1))))
      (check-normalization-reference :rmsnorm a -1 '(2) :weights (ct:full '(2 1 4) 2 :dtype dtype)))
    (let ((a (ct:from-data '(1000 1001 1002) :dtype dtype)))
      (check-normalization-reference :softmax a -1 '(0))
      (is (< (abs (- 1 (ct:tref (ct:sum (ct:softmax a))))) 1d-6))
      (loop for shifted in (tensor-values (ct:softmax (ct:add a 1000)))
            for original in (tensor-values (ct:softmax a))
            do (is (< (abs (- shifted original)) 1d-6))))
    (check-normalization-reference :rmsnorm (ct:from-data '(3 4) :dtype dtype) -1 '(0)
                                   :weights (ct:from-data '(1 2) :dtype dtype) :epsilon 0)
    (is (equalp '(0 0 0) (tensor-values (ct:rmsnorm (ct:zeros '(3) :dtype dtype)))))
    (is (= 1 (ct:tref (ct:softmax (ct:from-data '(7) :dtype dtype)) 0))))
  (is (equalp '(0.25 0.25 0.25 0.25) (tensor-values (ct:softmax (ct:full '(4) -3)))))
  (let* ((x (ct:full '(2049) -17))
         (y (ct:ones '(2049))))
    (setf (ct:tref x 0) 0 (ct:tref y 0) 4096)
    (is (> (ct:tref (ct:softmax x) 0) (ct:tref (ct:softmax x :accumulate :f64) 0)))
    (is (> (ct:tref (ct:rmsnorm y) 0) (ct:tref (ct:rmsnorm y :accumulate :f64) 0)))))

(test normalization-layouts-and-aliases
  (dolist (dtype '(:f32 :f64))
    (let* ((a (ct:reshape (ct:arange 1 25 :dtype dtype) '(2 3 4)))
           (reverse (ct:slice a :selectors '((nil nil -1) :all (nil nil -1))))
           (permute (ct:transpose a :axes '(2 0 1)))
           (broadcast (ct:make-tensor-view (ct:tensor-storage a) '(2 3 4) :strides '(0 4 1))))
      (dolist (input (list reverse permute broadcast))
        (dolist (accumulate '(nil :f64))
          (check-normalization-reference :softmax input '(0 2) '(0 2) :accumulate accumulate)
          (check-normalization-reference :rmsnorm input 1 '(1) :accumulate accumulate)))
      (dolist (operation '(:softmax :rmsnorm))
        (let* ((function (ecase operation (:softmax #'ct:softmax!) (:rmsnorm #'ct:rmsnorm!)))
               (expected (ecase operation (:softmax (ct:softmax a :axis '(0 2)))
                                          (:rmsnorm (ct:rmsnorm a :axis '(0 2)))))
               (original (ct:copy-tensor a)))
          (dolist (out (list (ct:transpose (ct:zeros '(4 3 2) :dtype dtype) :axes '(2 1 0))
                            (ct:slice (ct:zeros '(2 3 8) :dtype dtype) :selectors '(:all :all (nil nil 2)))
                            reverse a))
            (ct:add! a original 0)
            (is (eq out (funcall function out a :axis '(0 2))))
            (is (equalp (tensor-values expected) (tensor-values out))))))
      (let* ((input (ct:from-data '((1 2 3) (4 5 6)) :dtype dtype))
             (weights (ct:slice input :selectors '(0 :all)))
             (expected (ct:rmsnorm input :weights weights)))
        (ct:rmsnorm! (ct:slice input :selectors '((nil nil -1) :all)) input :weights weights)
        (is (equalp (tensor-values expected)
                    (tensor-values (ct:slice input :selectors '((nil nil -1) :all)))))))))

(test normalization-validation-and-empty
  (dolist (function (list #'ct:softmax #'ct:rmsnorm))
    (dolist (shape '((0) (2 0) (0 3)))
      (is (zerop (ct:tensor-size (funcall function (ct:zeros shape)))))
      (is (zerop (ct:tensor-size (funcall function (ct:zeros shape) :axis 0)))))
    (dolist (dtype '(:s8 :u8 :c32 :c64 :f16 :bf16))
      (signals error (funcall function (ct:zeros '(0) :dtype dtype))))
    (signals error (funcall function (ct:from-data 3)))
    (signals error (funcall function (ct:ones '(2 3)) :axis '(0 -2)))
    (signals error (funcall function (ct:ones '(0)) :axis 1))
    (signals error (funcall function (ct:ones '(0)) :accumulate :f32)))
  (is (= 1 (ct:tref (ct:softmax (ct:from-data 3) :axis nil))))
  (is (= 1 (ct:tref (ct:softmax (ct:from-data 3) :axis #()))))
  (check-normalization-reference :rmsnorm (ct:from-data 3) nil nil)
  (dolist (epsilon '(-1 :bad #c(1 2)))
    (signals error (ct:rmsnorm (ct:zeros '(0)) :epsilon epsilon)))
  (dolist (weights (list (ct:ones '(1) :dtype :f64) (ct:ones '(2 1 3)) (ct:ones '(4)) :bad))
    (signals error (ct:rmsnorm (ct:ones '(2 3)) :weights weights)))
  (dolist (function (list #'ct:softmax! #'ct:rmsnorm!))
    (let ((out (ct:full '(2 3) 77)))
      (dolist (args (list (list out (ct:ones '(2 3)) :axis 2)
                         (list out (ct:ones '(2 3)) :accumulate :f32)
                         (list out (ct:ones '(2 3) :dtype :f64))
                         (list out (ct:ones '(3 2)))))
        (signals error (apply function args))
        (is (every (lambda (x) (= x 77)) (tensor-values out)))))
    (let* ((storage (ct:tensor-storage (ct:full '(6) 77)))
           (overlap (ct:make-tensor-view storage '(2 3) :strides '(0 1))))
      (signals error (funcall function overlap (ct:ones '(2 3))))
      (is (every (lambda (x) (= x 77)) (coerce storage 'list))))
    (let ((out (ct:zeros '(2 0))))
      (is (eq out (funcall function out out)))
      (signals error (funcall function out (ct:zeros '(0 2)))))
    (signals error (funcall function nil (ct:ones '(1)))))
  (let ((out (ct:full '(2 3) 77)))
    (signals error (ct:rmsnorm! out (ct:ones '(2 3)) :epsilon -1))
    (signals error (ct:rmsnorm! out (ct:ones '(2 3)) :weights (ct:ones '(4))))
    (is (every (lambda (x) (= x 77)) (tensor-values out)))))

(test normalization-foreign-storage
  (dolist (dtype '(:f32 :f64))
    (let ((foreign (if (eq dtype :f32) :float :double)))
      (cffi:with-foreign-object (pointer foreign 24)
        (let* ((storage (trivial-simd:make-vector-view pointer dtype 24))
               (input (ct:make-tensor-view storage '(2 3) :offset 2 :strides '(6 -1)))
               (other (trivial-simd:make-vector-view (cffi:inc-pointer pointer (* 2 (ct:dtype-bytes dtype)))
                                                   dtype 22))
               (out (ct:make-tensor-view other '(2 3) :strides '(-3 1) :offset 6)))
          (dotimes (i 24) (setf (cl-tensor::storage-ref storage i) (ct::coerce-value (1+ i) dtype)))
          (dolist (operation '(:softmax :rmsnorm))
            (check-normalization-reference operation input -1 '(1) :accumulate :f64)
            (let* ((original (ct:copy-tensor input))
                   (weights (ct:slice input :selectors '(0 :all)))
                   (expected (ecase operation (:softmax (ct:softmax input :accumulate :f64))
                                              (:rmsnorm (ct:rmsnorm input :weights weights :accumulate :f64)))))
              (ecase operation
                (:softmax (ct:softmax! out input :accumulate :f64))
                (:rmsnorm (ct:rmsnorm! out input :weights weights :accumulate :f64)))
              (is (equalp (tensor-values expected) (tensor-values out)))
              (ct:add! input original 0)))
          (let* ((original (ct:copy-tensor input))
                 (expected (ct:rmsnorm original :weights original :axis 0)))
            (ct:rmsnorm! input input :weights original :axis 0)
            (is (equalp (tensor-values expected) (tensor-values input)))))))))

(test normalization-seeded-reference
  (let ((state #+sbcl (sb-ext:seed-random-state 20261021)
               #-sbcl (make-random-state t)))
    (dotimes (trial 150)
      (let* ((dtype (if (zerop (mod trial 2)) :f32 :f64))
             (shape (loop repeat 3 collect (1+ (random 4 state))))
             (base (ct:make-tensor shape :dtype dtype)))
        (dolist (index (all-indices shape))
          (setf (apply #'ct:tref base index) (/ (- (random 17 state) 8) 4)))
        (let* ((input (if (zerop (random 2 state)) (ct:transpose base :axes '(2 0 1))
                          (ct:slice base :selectors '((nil nil -1) :all (nil nil -1)))))
               (axes (loop for a below 3 when (zerop (random 2 state)) collect a))
               (axis (coerce axes 'vector)))
          (dolist (accumulate '(nil :f64))
            (check-normalization-reference :softmax input axis axes :accumulate accumulate)
            (check-normalization-reference :rmsnorm input axis axes :weights 1.5 :epsilon 0.01
                                           :accumulate accumulate)))))))
