(require :asdf)
(asdf:load-system :cl-tensor)

(trivial-simd:define-kernel benchmark-softmax (x)
  (/ (exp (- x (trivial-simd:maximum x)))
     (trivial-simd:sum (exp (- x (trivial-simd:maximum x))))))
(trivial-simd:define-kernel benchmark-exponentials (x)
  (exp (- x (trivial-simd:maximum x))))
(trivial-simd:define-kernel benchmark-squares (x) (* x x))
(trivial-simd:define-kernel benchmark-sum-squares (x) (trivial-simd:sum (* x x)))

(defmacro define-benchmark-kernel-rows ()
  `(progn
     ,@(loop for dtype in '(:f32 :f64)
             for type in '(single-float double-float)
             for foreign in '(:float :double)
             collect
             `(defun ,(intern (format nil "BENCHMARK-KERNEL-~A" dtype))
                  (operation destination input input-start destination-start width epsilon)
                (declare (type (simple-array ,type (*)) destination)
                         (type fixnum input-start destination-start width)
                         (type ,type epsilon)
                         (optimize (speed 3) (safety 1)))
                (if (and (eq operation :softmax) (not *benchmark-wide*))
                    (benchmark-softmax destination input :x-start input-start
                                       :destination-start destination-start :end width)
                    (let ((total 0d0)
                          (pointer (when (trivial-simd:vector-view-p input)
                                     (trivial-simd:vector-view-pointer input))))
                      (declare (type double-float total))
                      (cond ((eq operation :softmax)
                             (benchmark-exponentials destination input :x-start input-start
                                                     :destination-start destination-start :end width)
                             (dotimes (i width)
                               (incf total (float (aref destination (+ destination-start i)) 1d0))))
                            (*benchmark-wide*
                             (benchmark-squares destination input :x-start input-start
                                                :destination-start destination-start :end width)
                             (dotimes (i width)
                               (incf total (float (aref destination (+ destination-start i)) 1d0))))
                            (t (setf total (float (benchmark-sum-squares input :x-start input-start :end width)
                                                  1d0))))
                      (let ((scale (if (eq operation :softmax)
                                       (coerce (/ 1d0 total) ',type)
                                       (/ ,(coerce 1 type)
                                          (sqrt (+ epsilon (coerce (/ total width) ',type)))))))
                        (declare (type ,type scale))
                        (dotimes (i width)
                          (setf (aref destination (+ destination-start i))
                                (* scale
                                   (if (eq operation :softmax)
                                       (aref destination (+ destination-start i))
                                       (if pointer
                                           (cffi:mem-aref pointer ,foreign (+ input-start i))
                                           (aref (the (simple-array ,type (*)) input) (+ input-start i))))))))))))))

(defvar *benchmark-wide* nil)
(define-benchmark-kernel-rows)

(defun benchmark-kernel-row-function (dtype accumulate)
  (setf *benchmark-wide* (and accumulate (eq dtype :f32)))
  (ecase dtype (:f32 #'benchmark-kernel-f32) (:f64 #'benchmark-kernel-f64)))

(defun normalization-benchmark-time (function)
  (dotimes (i 3) (funcall function))
  (let ((iterations 1) (target (* 0.005 internal-time-units-per-second)))
    (loop
      (let ((start (get-internal-real-time)))
        (dotimes (i iterations) (funcall function))
        (when (>= (- (get-internal-real-time) start) target) (return)))
      (setf iterations (* 2 iterations)))
    (let ((times (loop repeat 3 collect
                      (let ((start (get-internal-real-time)))
                        (dotimes (i iterations) (funcall function))
                        (* 1d6 (/ (- (get-internal-real-time) start)
                                  internal-time-units-per-second iterations)))))
          (count (min iterations 100)))
      #+sbcl (sb-ext:gc :full t)
      (let ((before #+sbcl (sb-ext:get-bytes-consed) #-sbcl 0))
        (dotimes (i count) (funcall function))
        (values (second (sort times #'<))
                #+sbcl (/ (- (sb-ext:get-bytes-consed) before) (float count 1d0))
                #-sbcl nil)))))

(defun benchmark-normalization-reference (operation input)
  (let* ((matrix (cl-tensor:copy-tensor input))
         (source (cl-tensor:tensor-storage matrix))
         (rows (aref (cl-tensor:tensor-shape input) 0))
         (width (aref (cl-tensor:tensor-shape input) 1))
         (result (make-array (* rows width) :element-type 'double-float)))
    (dotimes (row rows)
      (let* ((start (* row width))
             (maximum (loop for i below width maximize (aref source (+ start i))))
             (total (loop for i below width for x = (float (aref source (+ start i)) 1d0)
                          sum (if (eq operation :softmax) (exp (- x maximum)) (* x x)) into value double-float
                          finally (return value))))
        (dotimes (i width)
          (let ((x (float (aref source (+ start i)) 1d0)))
            (setf (aref result (+ start i))
                  (if (eq operation :softmax) (/ (exp (- x maximum)) total)
                      (* 1.5d0 (/ x (sqrt (+ (float 1e-6 1d0) (/ total width)))))))))))
    result))

(defun check-benchmark-normalization (actual reference dtype)
  (let ((storage (cl-tensor:tensor-storage actual))
        (tolerance (if (eq dtype :f32) 1d-5 1d-12)))
    (dotimes (i (length reference))
      (unless (<= (abs (- (aref storage i) (aref reference i)))
                  (* tolerance (+ 1d0 (abs (aref reference i)))))
        (error "Normalization benchmark mismatch at ~D: ~S vs ~S"
               i (aref storage i) (aref reference i))))))

(defun normalization-benchmark-case (backend dtype accumulate operation form rows width layout)
  (let* ((trivial-simd::*backend* backend)
         (size (* rows width))
         (storage (cl-tensor:tensor-storage (cl-tensor:zeros (list size) :dtype dtype)))
         (out (cl-tensor:zeros (list rows width) :dtype dtype))
         (typed (symbol-function 'cl-tensor::normalization-row-function))
         (foreign-pointer nil))
    (dotimes (i size) (setf (aref storage i) (cl-tensor::coerce-value (/ (- (mod i 17) 8) 4) dtype)))
    (unwind-protect
         (let* ((input
                  (ecase layout
                    (:contiguous (cl-tensor:make-tensor-view storage (list rows width)))
                    (:transpose (cl-tensor:make-tensor-view storage (list rows width) :strides (list 1 rows)))
                    (:reverse (cl-tensor:make-tensor-view storage (list rows width)
                                                         :strides (list width -1) :offset (1- width)))
                    (:foreign
                     (setf foreign-pointer (cffi:foreign-alloc (if (eq dtype :f32) :float :double) :count size))
                     (let ((view (trivial-simd:make-vector-view foreign-pointer dtype size)))
                       (trivial-simd:copy! view storage)
                       (cl-tensor:make-tensor-view view (list rows width))))))
                (reference (benchmark-normalization-reference operation input))
                (function (ecase operation
                            (:softmax (if (eq form :out) #'cl-tensor:softmax! #'cl-tensor:softmax))
                            (:rmsnorm (if (eq form :out) #'cl-tensor:rmsnorm! #'cl-tensor:rmsnorm))))
                (arguments (append (when (eq form :out) (list out)) (list input :accumulate accumulate)
                                   (when (eq operation :rmsnorm) (list :weights 1.5)))))
           (dolist (path '(:typed :kernel))
             (setf (symbol-function 'cl-tensor::normalization-row-function)
                   (if (eq path :typed) typed #'benchmark-kernel-row-function))
             (check-benchmark-normalization (apply function arguments) reference dtype)
             (multiple-value-bind (time bytes)
                 (normalization-benchmark-time (lambda () (apply function arguments)))
               (format t "~(~A ~A ~A ~A ~A ~A ~D ~D ~A~) ~,4F ~,1F~%"
                       backend dtype (or accumulate :same) operation form path rows width layout time bytes))))
      (setf (symbol-function 'cl-tensor::normalization-row-function) typed)
      (when foreign-pointer (cffi:foreign-free foreign-pointer)))))

(unless (uiop:getenv "CT_NORMALIZATION_CHECK_ONLY")
  (format t "# ~A ~A, ~A, selected backend ~A~%" (lisp-implementation-type) (lisp-implementation-version)
          (machine-type) (trivial-simd:backend))
  (format t "# backend dtype accumulation operation form path rows width layout us/call bytes/call~%")
  (dolist (backend (remove-duplicates (list :lisp (trivial-simd:backend))))
    (dolist (dtype '(:f32 :f64))
      (dolist (accumulate '(nil :f64))
        (dolist (operation '(:softmax :rmsnorm))
          (dolist (form '(:allocating :out))
            (dolist (rows '(1 32))
              (dolist (width '(32 128 512 4096 32768))
                (dolist (layout '(:contiguous :transpose :reverse :foreign))
                  (normalization-benchmark-case backend dtype accumulate operation form rows width layout))))))))))
