(in-package #:cl-tensor/tests)

(in-suite :cl-tensor)

(test reduction-values-and-dtypes
  (dolist (dtype '(:f32 :f64 :c32 :c64 :s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64))
    (let ((a (ct:from-data '((3 1 2) (4 6 5)) :dtype dtype)))
      (is (= 21 (ct:tref (ct:sum a))))
      (is (eq dtype (ct:tensor-dtype (ct:sum a))))
      (is (equalp '(6 15) (tensor-values (ct:sum a :axis -1))))
      (is (equalp '(7 7 7) (tensor-values (ct:sum a :axis 0))))
      (is (equalp '(6 120) (tensor-values (ct:prod a :axis 1))))
      (is (equalp '(2 5) (tensor-values (ct:mean a :axis 1))))
      (is (= 7/2 (ct:tref (ct:mean a))))
      (is (eq (if (member dtype '(:f32 :f64 :c32 :c64)) dtype :f64)
              (ct:tensor-dtype (ct:mean a))))
      (is (equalp #(2 1) (ct:tensor-shape (ct:sum a :axis 1 :keepdims t))))
      (is (equalp #(1 1) (ct:tensor-shape (ct:sum a :keepdims t))))
      (is (equalp (tensor-values a) (tensor-values (ct:sum a :axis #()))))
      (unless (member dtype '(:c32 :c64))
        (is (equalp '(1 4) (tensor-values (ct:minimum a :axis 1))))
        (is (equalp '(4 6 5) (tensor-values (ct:maximum a :axis 0))))
        (is (equal '(1 0) (tensor-values (ct:argmin a :axis 1))))
        (is (equal '(0 1) (tensor-values (ct:argmax a :axis 1))))
        (is (= 4 (ct:tref (ct:argmax a))))
        (is (eq :s64 (ct:tensor-dtype (ct:argmax a)))))))
  (is (= -16 (ct:tref (ct:prod (ct:from-data '(20 12) :dtype :s8)))))
  (is (= -128 (ct:tref (ct:sum (ct:from-data '(127 1) :dtype :s8)))))
  (is (= 127d0 (ct:tref (ct:mean (ct:from-data '(127 127) :dtype :s8)))))
  (is (eq :f64 (ct:tensor-dtype (ct:sum (ct:ones '(2)) :accumulate :f64))))
  (is (eq :c64 (ct:tensor-dtype (ct:mean (ct:ones '(2) :dtype :c32) :accumulate :f64))))
  (is (= 1d0 (ct:tref (ct:sum (ct:from-data '(1f8 1f0 -1f8)) :accumulate :f64))))
  (is (= #c(0f0 2f0) (ct:tref (ct:prod (ct:from-data '(#c(1 1) #c(1 1)) :dtype :c32))))))

(test reduction-layouts-and-indices
  (let* ((a (ct:reshape (ct:arange 24) '(2 3 4)))
         (reverse (ct:slice a :selectors '((nil nil -1) :all (nil nil -1))))
         (permute (ct:transpose a :axes '(2 0 1))))
    (is (equalp '(60 92 124) (tensor-values (ct:sum a :axis '(2 0)))) )
    (is (equal '(7 7 7) (tensor-values (ct:argmax a :axis '(2 0)))))
    (is (equal '(0 0 0) (tensor-values (ct:argmax reverse :axis '(0 2)))))
    (is (= 23 (ct:tref (ct:argmax permute))))
    (is (equalp '(60 92 124) (tensor-values (ct:sum reverse :axis '(0 2))))))
  (let* ((a (ct:from-data '(9 9 2 9)))
         (r (ct:slice a :selectors '((nil nil -1)))))
    (is (= 0 (ct:tref (ct:argmax r))))
    (is (= 1 (ct:tref (ct:argmin r)))))
  (let ((a (ct:make-tensor-view (ct:tensor-storage (ct:from-data '(3 1 2))) '(2 3) :strides '(0 1))))
    (is (= 12 (ct:tref (ct:sum a))))
    (is (equal '(0 0 0) (tensor-values (ct:argmax a :axis 0))))
    (is (= 1 (ct:tref (ct:argmin a)))))
  (let ((a (ct:from-data '(0f0 -0f0))))
    (is (= 0 (ct:tref (ct:argmin a))))
    (is (= 0 (ct:tref (ct:argmax a))))))

(test reduction-empty-and-errors
  (is (= 0 (ct:tref (ct:sum (ct:zeros '(0))))))
  (is (= 1 (ct:tref (ct:prod (ct:zeros '(0))))))
  (is (equalp '(0 0) (tensor-values (ct:sum (ct:zeros '(2 0)) :axis 1))))
  (is (equalp '(1 1) (tensor-values (ct:prod (ct:zeros '(2 0)) :axis 1))))
  (is (zerop (ct:tensor-size (ct:mean (ct:zeros '(0 0)) :axis 1))))
  (dolist (fun (list #'ct:mean #'ct:minimum #'ct:maximum #'ct:argmin #'ct:argmax))
    (signals error (funcall fun (ct:zeros '(2 0)) :axis 1)))
  (dolist (fun (list #'ct:sum #'ct:mean #'ct:prod #'ct:minimum #'ct:maximum #'ct:argmin #'ct:argmax))
    (signals error (funcall fun (ct:ones '(1) :dtype :f16)))
    (signals error (funcall fun (ct:ones '(2 3)) :axis '(0 -2)))
    (signals error (funcall fun (ct:ones '(2 3)) :axis 2)))
  (signals error (ct:sum (ct:ones '(1) :dtype :s8) :accumulate :f64))
  (signals error (ct:sum (ct:ones '(1)) :accumulate :f32))
  (signals error (ct:minimum (ct:ones '(0) :dtype :c32)))
  (is (= 5 (ct:tref (ct:sum (ct:from-data 5)))))
  (is (= 0 (ct:tref (ct:argmin (ct:from-data 5)))))
  (signals error (ct:sum (ct:from-data 5) :axis 0)))

(test reduction-out-and-aliases
  (let* ((a (ct:from-data '((3 1 2) (4 6 5))))
         (out (ct:slice (ct:arange 4) :selectors '((3 nil -2)))))
    (dolist (pair (list (cons #'ct:sum! '(6 15)) (cons #'ct:mean! '(2 5))
                       (cons #'ct:minimum! '(1 4)) (cons #'ct:maximum! '(3 6))
                       (cons #'ct:prod! '(6 120))))
      (is (eq out (funcall (car pair) out a :axis 1)))
      (is (equalp (cdr pair) (tensor-values out))))
    (let ((i (ct:zeros '(2) :dtype :s64)))
      (is (eq i (ct:argmin! i a :axis 1)))
      (is (equal '(1 0) (tensor-values i)))
      (is (eq i (ct:argmax! i a :axis 1)))
      (is (equal '(0 1) (tensor-values i))))
    (let ((aliased (ct:slice a :selectors '(0 (0 2)))))
      (ct:sum! aliased a :axis 1)
      (is (equalp '(6 15) (tensor-values aliased))))
    (let ((bad (ct:make-tensor-view (ct:tensor-storage a) '(2) :strides '(0))))
      (signals error (ct:sum! bad a :axis 1)))
    (signals error (ct:sum! (ct:zeros '(3)) a :axis 1))
    (signals error (ct:sum! (ct:zeros '(2) :dtype :f64) a :axis 1)))
  (let ((out (ct:full '(2) 77)))
    (signals error (ct:mean! out (ct:zeros '(2 0)) :axis 1))
    (is (equalp '(77 77) (tensor-values out)))))

(test shape-and-reduction-foreign-storage
  (cffi:with-foreign-object (pointer :float 8)
    (dotimes (i 8) (setf (cffi:mem-aref pointer :float i) (float i 0f0)))
    (let* ((storage (trivial-simd:make-vector-view pointer :f32 8))
           (a (ct:make-tensor-view storage '(2 3) :offset 1))
           (out (ct:make-tensor-view storage '(2) :offset 3 :strides '(-1))))
      (is (equalp '(1 4 2 5 3 6) (tensor-values (ct:transpose a))))
      (is (equalp '(1 2 3 4 5 6) (tensor-values (ct:concatenate (ct:split a 2)))))
      (ct:sum! out a :axis 1)
      (is (equalp '(6 15) (tensor-values out))))))

(defun reference-reduction-groups (tensor axes)
  (let* ((shape (coerce (ct:tensor-shape tensor) 'list))
         (kept (loop for a below (length shape) unless (member a axes) collect a)))
    (loop for output in (all-indices (mapcar (lambda (a) (nth a shape)) kept))
          collect (loop for reduced in (all-indices (mapcar (lambda (a) (nth a shape)) axes))
                        collect (apply #'ct:tref tensor
                                       (loop for a below (length shape)
                                             collect (if (member a axes)
                                                         (nth (position a axes) reduced)
                                                         (nth (position a kept) output))))))))

(test random-reductions-match-enumeration
  (dotimes (trial 250)
    (let* ((shape (loop repeat (random-between 0 3) collect (random-between 0 3)))
           (rank (length shape))
           (strides (loop repeat rank collect (random-between -5 5)))
           (storage (make-array 100 :element-type 'double-float
                                    :initial-contents (loop for i below 100 collect (float (1+ (mod i 3)) 0d0))))
           (tensor (ct:make-tensor-view storage shape :dtype :f64 :strides strides :offset 40))
           (axes (loop for a below rank when (= 1 (random-between 0 1)) collect a))
           (groups (reference-reduction-groups tensor axes))
           (selector (coerce (reverse axes) 'vector)))
      (dolist (spec (list (cons #'ct:sum (lambda (g) (reduce #'+ g :initial-value 0d0)))
                         (cons #'ct:prod (lambda (g) (reduce #'* g :initial-value 1d0)))))
        (let ((expected (mapcar (cdr spec) groups)))
          (is (equalp expected (tensor-values (funcall (car spec) tensor :axis selector))))
          (is (equalp expected (tensor-values (funcall (car spec) tensor :axis selector :keepdims t))))))
      (when (every #'identity groups)
        (is (equalp (mapcar (lambda (g) (reduce #'min g)) groups)
                    (tensor-values (ct:minimum tensor :axis selector))))
        (is (equalp (mapcar (lambda (g) (reduce #'max g)) groups)
                    (tensor-values (ct:maximum tensor :axis selector))))
        (is (equal (mapcar (lambda (g) (position (reduce #'min g) g)) groups)
                   (tensor-values (ct:argmin tensor :axis selector))))
        (is (equal (mapcar (lambda (g) (position (reduce #'max g) g)) groups)
                   (tensor-values (ct:argmax tensor :axis selector))))
        (is (equalp (mapcar (lambda (g) (/ (reduce #'+ g) (length g))) groups)
                    (tensor-values (ct:mean tensor :axis selector))))))))

(test reduction-empty-view-offsets-and-integration
  (let ((a (ct:make-tensor-view (make-array 0 :element-type 'single-float) '(2 0) :offset 100)))
    (is (equalp '(0 0) (tensor-values (ct:sum a :axis 1))))
    (is (equalp '(1 1) (tensor-values (ct:prod a :axis 1)))))
  (let* ((a (ct:reshape (ct:arange 12) '(3 4)))
         (reversed (ct:slice a :selectors '(:all (nil nil -1))))
         (means (ct:mean reversed :axis 1 :keepdims t)))
    (is (equalp '(0 0 0) (tensor-values (ct:sum (ct:subtract reversed means) :axis 1))))
    (ct:add! reversed reversed 1)
    (is (= 1 (ct:tref a 0 0)))))
