(in-package #:cl-tensor/tests)

(in-suite :cl-tensor)

(defun reference-take (input indices axis)
  (let* ((axis (mod axis (ct:tensor-rank input)))
         (shape (append (subseq (coerce (ct:tensor-shape input) 'list) 0 axis)
                        (coerce (ct:tensor-shape indices) 'list)
                        (subseq (coerce (ct:tensor-shape input) 'list) (1+ axis))))
         (index-end (+ axis (ct:tensor-rank indices))))
    (values shape
            (mapcar (lambda (coordinates)
                      (let* ((index (apply #'ct:tref indices (subseq coordinates axis index-end)))
                             (size (aref (ct:tensor-shape input) axis)))
                        (apply #'ct:tref input
                               (append (subseq coordinates 0 axis)
                                       (list (if (minusp index) (+ size index) index))
                                       (subseq coordinates index-end)))))
                    (all-indices shape)))))

(test take-shapes-and-axes
  (let ((input (ct:reshape (ct:arange 24) '(2 3 4))))
    (dolist (axis '(0 1 2 -1 -2 -3))
      (dolist (data '(0 (0 -1 0) ((-1 0) (0 -1)) ()))
        (let* ((indices (ct:from-data data :dtype :s64))
               (result (ct:take input indices :axis axis)))
          (multiple-value-bind (shape values) (reference-take input indices axis)
            (is (equalp shape (coerce (ct:tensor-shape result) 'list)))
            (is (equalp values (tensor-values result))))
          (is (ct:contiguous-p result))
          (is (not (eq (ct:tensor-storage result) (ct:tensor-storage input))))))))
  (is (= 9f0 (ct:tref (ct:take (ct:from-data '(7 8 9)) (ct:from-data -1 :dtype :s8)))))
  (let* ((input (ct:from-data '((1 2) (3 4))))
         (result (ct:take input (ct:from-data '(0) :dtype :u8))))
    (setf (ct:tref result 0 0) 99)
    (is (= 1f0 (ct:tref input 0 0)))))

(test take-dtypes-and-empty-inputs
  (dolist (dtype (mapcar #'ct:dtype-name ct:*dtypes*))
    (when (cl-tensor::builtin-dtype-p dtype)
      (let ((input (ct:zeros '(3 2) :dtype dtype)))
        (dotimes (i 3) (dotimes (j 2) (setf (ct:tref input i j) (+ (* i 2) j))))
        (let ((result (ct:take input (ct:from-data '(2 0) :dtype :u64))))
          (is (eq dtype (ct:tensor-dtype result)))
          (is (equalp '(4 5 0 1) (mapcar #'realpart (tensor-values result))))))))
  (dolist (dtype '(:s8 :u8 :s16 :u16 :s32 :u32 :s64 :u64))
    (is (= 8f0 (ct:tref (ct:take (ct:from-data '(7 8)) (ct:from-data 1 :dtype dtype))))))
  (dolist (dtype '(:f16 :bf16))
    (let ((input (ct:zeros '(3) :dtype dtype)))
      (loop for value in '(#x8000 #xffff #x7fc0) for i from 0
            do (setf (ct:tref input i) value))
      (is (equalp '(#x7fc0 #xffff #x8000)
                  (tensor-values (ct:take input (ct:from-data '(2 1 0) :dtype :u8)))))))
  (let ((empty (ct:from-data '() :dtype :s64)))
    (is (equalp #(0 3) (ct:tensor-shape (ct:take (ct:zeros '(0 3)) empty))))
    (is (equalp #(2 0 0) (ct:tensor-shape (ct:take (ct:zeros '(2 0))
                                                (ct:zeros '(2 0) :dtype :s64) :axis 0)))))
  (let ((indices (ct:from-data '(0) :dtype :s64)))
    (is (zerop (ct:tensor-size (ct:take (ct:zeros '(3 0)) indices))))
    (signals error (ct:take (ct:zeros '(0 3)) indices)))
  (signals error (ct:take (ct:from-data 1) (ct:from-data 0 :dtype :s64))))

(test take-validation-and-destination-guards
  (let ((input (ct:from-data '((1 2) (3 4))))
        (out (ct:full '(2 2) 99)))
    (dolist (data '((0 2) (0 -3)))
      (signals error (ct:take! out input (ct:from-data data :dtype :s64)))
      (is (equalp '(99f0 99f0 99f0 99f0) (tensor-values out))))
    (dolist (dtype '(:f32 :f64 :c32 :f16 :bf16))
      (signals error (ct:take input (ct:zeros '(0) :dtype dtype))))
    (dolist (axis '(2 -3 nil 0.5))
      (signals error (ct:take input (ct:from-data '(0) :dtype :s64) :axis axis)))
    (let ((indices (ct:from-data '(1 0) :dtype :s64)))
      (signals error (ct:take! (ct:zeros '(4)) input indices))
      (signals error (ct:take! (ct:zeros '(2 2) :dtype :f64) input indices))
      (signals error (ct:take! (ct:make-tensor-view (ct:tensor-storage out) '(2 2)
                                                 :strides '(0 1)) input indices))
      (is (equalp '(99f0 99f0 99f0 99f0) (tensor-values out)))))
  (signals error (ct:take (ct:zeros '(2 0)) (ct:from-data '(2) :dtype :s64)))
  (dolist (value '(-9223372036854775808 9223372036854775807))
    (signals error (ct:take (ct:zeros '(2)) (ct:from-data value :dtype :s64))))
  (signals error (ct:take (ct:zeros '(2)) (ct:from-data 18446744073709551615 :dtype :u64))))

(test take-strides-and-aliases
  (let* ((input (ct:transpose (ct:slice (ct:reshape (ct:arange 48) '(4 12))
                                       :selectors '((nil nil -1) (1 12 2)))))
         (indices (ct:slice (ct:from-data '(0 99 -1 99 1) :dtype :s64)
                           :selectors '((nil nil -2))))
         (out (ct:transpose (ct:zeros '(4 3)))))
    (multiple-value-bind (shape values) (reference-take input indices 0)
      (is (equalp shape '(3 4)))
      (is (eq out (ct:take! out input indices)))
      (is (equalp values (tensor-values out)))))
  (let* ((input (ct:make-tensor-view (ct:tensor-storage (ct:from-data '(7 8))) '(3 2)
                                    :strides '(0 1)))
         (indices (ct:make-tensor-view (ct:tensor-storage (ct:from-data '(1) :dtype :s64))
                                      '(2) :strides '(0))))
    (is (equalp '(7f0 8f0 7f0 8f0) (tensor-values (ct:take input indices)))))
  (let* ((input (ct:from-data '((1 2) (3 4))))
         (indices (ct:from-data '(1 0) :dtype :s64)))
    (is (eq input (ct:take! input input indices)))
    (is (equalp '(3f0 4f0 1f0 2f0) (tensor-values input))))
  (let* ((input (ct:from-data '(10 20 30) :dtype :s64))
         (indices (ct:from-data '(2 0 1) :dtype :s64)))
    (is (eq indices (ct:take! indices input indices)))
    (is (equalp '(30 10 20) (tensor-values indices))))
  (let* ((storage (ct:tensor-storage (ct:arange 6)))
         (input (ct:make-tensor-view storage '(3) :offset 0))
         (out (ct:make-tensor-view storage '(3) :strides '(-1) :offset 3)))
    (ct:take! out input (ct:from-data '(2 0 1) :dtype :s64))
    (is (equalp '(2f0 0f0 1f0) (tensor-values out)))
    (is (= 4f0 (aref storage 4)))
    (is (= 5f0 (aref storage 5)))))

(test take-foreign-storage
  (cffi:with-foreign-objects ((data :float 8) (ids :int64 4))
    (dotimes (i 8) (setf (cffi:mem-aref data :float i) (float i 1f0)))
    (dotimes (i 4) (setf (cffi:mem-aref ids :int64 i) (if (evenp i) 2 0)))
    (let* ((input (ct:make-tensor-view (trivial-simd:make-vector-view data :f32 8) '(3 2)))
           (indices (ct:make-tensor-view (trivial-simd:make-vector-view ids :s64 4)
                                        '(2) :strides '(-2) :offset 2))
           (out (ct:make-tensor-view
                 (trivial-simd:make-vector-view (cffi:inc-pointer data 8) :f32 6) '(2 2)
                 :strides '(2 -1) :offset 1)))
      (is (equalp '(4f0 5f0 4f0 5f0) (tensor-values (ct:take input indices))))
      (ct:take! out input indices)
      (is (equalp '(4f0 5f0 4f0 5f0) (tensor-values out)))
      (is (= 0f0 (cffi:mem-aref data :float 0)))
      (is (= 7f0 (cffi:mem-aref data :float 7))))))

(test take-seeded-coordinate-reference
  (dotimes (trial 150)
    (let* ((shape (loop repeat (random-between 1 4) collect (random-between 1 4)))
           (axis (random-between 0 (1- (length shape))))
           (input (ct:transpose (ct:reshape (ct:arange (reduce #'* shape)) (reverse shape))))
           (index-shape (loop repeat (random-between 0 3) collect (random-between 0 3)))
           (indices (ct:zeros index-shape :dtype :s64)))
      (dolist (coordinates (all-indices index-shape))
        (setf (apply #'ct:tref indices coordinates)
              (random-between (- (nth axis shape)) (1- (nth axis shape)))))
      (multiple-value-bind (expected-shape values) (reference-take input indices axis)
        (let ((result (ct:take input indices :axis axis)))
          (is (equalp expected-shape (coerce (ct:tensor-shape result) 'list)))
          (is (equalp values (tensor-values result))))))))

(test reshape-views-and-copies
  (let* ((a (ct:arange 12)) (b (ct:reshape a '(2 3 2)))
         (flat (ct:reshape b '(-1))))
    (is (eq (ct:tensor-storage a) (ct:tensor-storage b)))
    (is (equalp #(12) (ct:tensor-shape flat)))
    (setf (ct:tref b 1 2 1) 99)
    (is (= 99 (ct:tref a 11)))
    (let ((copy (ct:reshape a '(3 4) :copy :always)))
      (is (not (eq (ct:tensor-storage a) (ct:tensor-storage copy))))
      (setf (ct:tref copy 0 0) 42)
      (is (= 0 (ct:tref a 0)))))
  (let* ((a (ct:reshape (ct:arange 6) '(2 3))) (b (ct:transpose a)))
    (signals error (ct:reshape b '(6) :copy :never))
    (let ((flat (ct:reshape b '(6))))
      (is (equalp '(0 3 1 4 2 5) (tensor-values flat)))
      (is (not (eq (ct:tensor-storage flat) (ct:tensor-storage a))))))
  (let* ((a (ct:slice (ct:arange 12) :selectors '((nil nil 2))))
         (b (ct:reshape a '(2 3) :copy :never)))
    (is (equalp '(0 2 4 6 8 10) (tensor-values b)))
    (is (eq (ct:tensor-storage a) (ct:tensor-storage b))))
  (let* ((a (ct:slice (ct:arange 6) :selectors '((nil nil -1))))
         (b (ct:reshape a '(2 3) :copy :never)))
    (is (equalp '(5 4 3 2 1 0) (tensor-values b)))
    (is (equalp #(-3 -1) (ct:tensor-strides b))))
  (let* ((a (ct:make-tensor-view (ct:tensor-storage (ct:ones '(1))) '(2 3) :strides '(0 0)))
         (b (ct:reshape a '(6) :copy :never)))
    (is (equalp '(1 1 1 1 1 1) (tensor-values b)))
    (is (equalp #(0) (ct:tensor-strides b))))
  (let ((a (ct:zeros '(0 2))))
    (is (eq (ct:tensor-storage a) (ct:tensor-storage (ct:reshape a '(2 0 3)))))
    (is (equalp #(0 2) (ct:tensor-shape (ct:reshape a '(-1 2)))))
    (signals error (ct:reshape a '(0 -1))))
  (is (= 7 (ct:tref (ct:reshape (ct:from-data 7) '(1 1)) 0 0)))
  (signals error (ct:reshape (ct:arange 5) '(2 3)))
  (signals error (ct:reshape (ct:arange 6) '(-1 -1)))
  (signals error (ct:reshape (ct:arange 6) '(6) :copy t)))

(test shape-view-operations
  (let* ((a (ct:reshape (ct:arange 6) '(1 2 3)))
         (b (ct:transpose a :axes '(2 0 1)))
         (s (ct:squeeze a))
         (e (ct:expand-dims s :axis -1)))
    (is (equalp #(3 1 2) (ct:tensor-shape b)))
    (is (equalp '(0 3 1 4 2 5) (tensor-values b)))
    (is (equalp #(2 3) (ct:tensor-shape s)))
    (is (equalp #(2 3 1) (ct:tensor-shape e)))
    (setf (ct:tref e 1 2 0) 77)
    (is (= 77 (ct:tref a 0 1 2)))
    (is (equalp #(1 2 3) (ct:tensor-shape (ct:squeeze a :axis #()))))
    (signals error (ct:squeeze a :axis 1))
    (signals error (ct:transpose a :axes '(0 0 2)))
    (signals error (ct:transpose a :axes '(0 1)))
    (signals error (ct:expand-dims a))
    (signals error (ct:expand-dims a :axis 4)))
  (is (zerop (ct:tensor-rank (ct:transpose (ct:from-data 2)))))
  (is (zerop (ct:tensor-rank (ct:squeeze (ct:ones '(1 1)))))))

(test slicing-views
  (let ((a (ct:reshape (ct:arange 12) '(3 4))))
    (is (equalp '(8 9 10 11) (tensor-values (ct:slice a :selectors '(-1)))))
    (is (equalp '(3 2 1 0 7 6 5 4 11 10 9 8)
                (tensor-values (ct:slice a :selectors '(:all (nil nil -1))))))
    (is (equalp '(1 3 5 7) (tensor-values (ct:slice a :selectors '((0 2) (1 4 2))))))
    (is (equalp '(0 1 2 3) (tensor-values (ct:slice a :selectors '((-99 1) :all)))))
    (is (equalp #(0 4) (ct:tensor-shape (ct:slice a :selectors '((2 1) :all)))))
    (is (zerop (ct:tensor-size (ct:slice a :selectors '(:all (3 -1 -1))))))
    (let ((v (ct:slice a :selectors '(1 (nil nil -1)))))
      (setf (ct:tref v 0) 50)
      (is (= 50 (ct:tref a 1 3))))
    (is (zerop (ct:tensor-rank (ct:slice a :selectors '(0 0)))))
    (signals error (ct:slice a :selectors '(3)))
    (signals error (ct:slice a :selectors '(0 0 0)))
    (signals error (ct:slice a :selectors '((nil nil 0)))))
  (is (zerop (ct:tensor-size (ct:slice (ct:zeros '(0 3)) :selectors '((nil nil -1)))))))

(test joining-and-splitting
  (let* ((a (ct:reshape (ct:arange 6) '(2 3)))
         (joined (ct:concatenate (list a (ct:transpose (ct:transpose a))) :axis -1))
         (parts (ct:split joined 2 :axis 1)))
    (is (equalp #(2 6) (ct:tensor-shape joined)))
    (is (equalp '(0 1 2 0 1 2 3 4 5 3 4 5) (tensor-values joined)))
    (is (equalp '(0 1 2 3 4 5) (tensor-values (first parts))))
    (setf (ct:tref (second parts) 0 0) 90)
    (is (= 90 (ct:tref joined 0 3)))
    (is (= 0 (ct:tref a 0 0)))
    (is (equalp #(2 3 2) (ct:tensor-shape (ct:stack (list a a) :axis -1))))
    (is (equalp '(0 0 1 1 2 2 3 3 4 4 5 5) (tensor-values (ct:stack (list a a) :axis -1))))
    (is (equal '(0 4 0 8) (mapcar #'ct:tensor-size (ct:split joined '(0 2 2) :axis 1))))
    (signals error (ct:split a 2 :axis 1))
    (signals error (ct:split a '(2 1) :axis 1))
    (signals error (ct:split a '(4) :axis 1))
    (signals error (ct:concatenate (list a (ct:zeros '(3 3))) :axis 1))
    (signals error (ct:stack (list a (ct:zeros '(3 2))))))
  (is (equalp '(1 2) (tensor-values (ct:stack (list (ct:from-data 1) (ct:from-data 2))))))
  (is (every #'zerop (mapcar #'ct:tensor-size (ct:split (ct:zeros '(0)) 3))))
  (dolist (dtype '(:f16 :bf16))
    (let* ((a (ct:make-tensor-view (make-array 2 :element-type '(unsigned-byte 16) :initial-contents '(1 65535)) '(2) :dtype dtype))
           (b (ct:concatenate (list a a))))
      (is (equal '(1 65535 1 65535) (tensor-values b)))
      (is (eq dtype (ct:tensor-dtype b)))))
  (signals error (ct:concatenate nil))
  (signals error (ct:stack nil))
  (signals error (ct:concatenate (list (ct:from-data 1))))
  (signals error (ct:concatenate (list (ct:ones '(1)) (ct:ones '(1) :dtype :f64)))))

(test random-reshape-preserves-logical-order
  (dotimes (trial 250)
    (let* ((shape (loop repeat (random-between 0 3) collect (random-between 0 3)))
           (strides (loop repeat (length shape) collect (random-between -5 5)))
           (a (ct:make-tensor-view (ct:tensor-storage (ct:arange 100)) shape :strides strides :offset 40))
           (size (ct:tensor-size a))
           (target (list 1 size 1))
           (b (ct:reshape a target)))
      (is (equalp target (coerce (ct:tensor-shape b) 'list)))
      (is (equalp (tensor-values a) (tensor-values b)))
      (is (equalp (tensor-values a) (tensor-values (ct:reshape a target :copy :always))))
      (let ((view (handler-case (ct:reshape a target :copy :never) (error () nil))))
        (let* ((visited (mapcar (lambda (indices) (ct:tensor-index a indices))
                               (all-indices shape)))
               (affine (or (<= size 1)
                           (let ((stride (- (second visited) (first visited))))
                             (loop for index in visited for i from 0
                                   always (= index (+ (first visited) (* i stride))))))))
          (is (eq affine (and view t))))
        (when view
          (is (eq (ct:tensor-storage view) (ct:tensor-storage a)))
          (is (equalp (tensor-values a) (tensor-values view))))))))

(test reshape-does-not-modify-shape
  (let ((shape (list -1 2)))
    (ct:reshape (ct:arange 6) shape)
    (is (equal '(-1 2) shape))))
