(require :asdf)
(asdf:load-system :cl-tensor)

(defpackage #:cl-tensor/examples
  (:use #:cl)
  (:local-nicknames (#:ct #:cl-tensor)))

(in-package #:cl-tensor/examples)

(let ((sequence (ct:arange 5 0 -2 :dtype :s8))
      (samples (ct:linspace 0 1 :num 3))
      (identity (ct:eye 2 :columns 3 :k 1)))
  (assert (= 3 (ct:tref sequence 1)))
  (assert (= 0.5f0 (ct:tref samples 1)))
  (assert (= 1f0 (ct:tref identity 1 2))))

(let* ((rows (ct:from-data '((1) (2))))
       (columns (ct:from-data '(10 20 30)))
       (sum (ct:add rows columns))
       (mask (ct:compare :gt sum 20))
       (selected (ct:select mask sum 0))
       (out (ct:zeros '(2 3))))
  (assert (= 32f0 (ct:tref sum 1 2)))
  (assert (= 0f0 (ct:tref selected 0 0)))
  (ct:multiply! out selected 2)
  (assert (= 64f0 (ct:tref out 1 2)))
  (let ((copy (ct:copy-tensor out)))
    (setf (ct:tref copy 0 0) 7)
    (assert (= 0f0 (ct:tref out 0 0))))
  (assert (= 64 (ct:tref (ct:astype out :s16) 1 2))))

(let* ((values (ct:from-data '(1 2 3)))
       (bits (ct:astype values :bf16)))
  (assert (= 2f0 (ct:tref (ct:astype bits :f32) 1))))

(format t "Constructor, broadcasting and conversion examples passed.~%")

(let* ((matrix (ct:reshape (ct:arange 12) '(3 4)))
       (reversed (ct:slice matrix :selectors '(:all (nil nil -1))))
       (means (ct:mean reversed :axis 1 :keepdims t))
       (centered (ct:subtract reversed means)))
  (format t "~&Reversed rows: ~S~%Row means: ~S~%Centered row sums: ~S~%"
          (ct:tensor-shape reversed) (ct:tensor-storage means)
          (ct:tensor-storage (ct:sum centered :axis 1))))

(let* ((matrix (ct:from-data '((1 2 3) (4 5 6))))
       (vector (ct:from-data '(2 3 4)))
       (product (ct:matmul matrix vector))
       (out (ct:transpose (ct:zeros '(3 2))))
       (batches (ct:matmul (ct:ones '(2 1 3 4)) (ct:ones '(1 5 4 2)))))
  (assert (= 20f0 (ct:tref product 0)))
  (assert (= 47f0 (ct:tref product 1)))
  (ct:matmul! out matrix (ct:eye 3))
  (assert (= 6f0 (ct:tref out 1 2)))
  (assert (equalp #(2 5 3 2) (ct:tensor-shape batches)))
  (assert (= 4f0 (ct:tref batches 1 4 2 1)))
  (format t "~&Vector, matrix and batched matmul examples passed.~%"))

(let* ((a (ct:reshape (ct:arange 12) '(2 2 3)))
       (reversed (ct:slice a :selectors '((nil nil -1) :all (nil nil -1))))
       (out (ct:zeros '(2 2 2))))
  (ct:matmul! out reversed (ct:ones '(3 2)))
  (assert (= 21f0 (ct:tref out 0 0 0)))
  (assert (= 30f0 (ct:tref out 0 1 1)))
  (assert (= 3f0 (ct:tref out 1 0 0)))
  (format t "~&Reversed batch and matrix strides example passed.~%"))

(let* ((storage (ct:tensor-storage (ct:full '(17) -1)))
       (out (ct:make-tensor-view storage '(2 3 2) :strides '(8 2 3))))
  (ct:matmul! out (ct:ones '(2 3 4)) (ct:ones '(4 2)))
  (assert (= 4f0 (ct:tref out 1 2 1)))
  (assert (= -1f0 (aref storage 1)))
  (format t "~&Interleaved batched destination example passed.~%"))

(let* ((input (ct:from-data '((1 2 3) (4 5 6))))
       (reversed (ct:slice input :selectors '(:all (nil nil -1))))
       (out (ct:transpose (ct:zeros '(3 2)))))
  (ct:add! out reversed (ct:from-data '((10) (20))))
  (assert (= 13f0 (ct:tref out 0 0)))
  (assert (= 24f0 (ct:tref out 1 2)))
  (format t "~&N-D broadcasting into a transposed destination passed.~%"))

(let* ((x (ct:from-data '(-2 -1 0 1 2)))
       (sigmoid (ct:sigmoid x))
       (silu (ct:silu x))
       (gelu (ct:gelu x)))
  (assert (= 0.5 (ct:tref sigmoid 2)))
  (assert (= 0 (ct:tref silu 2)))
  (assert (= 0 (ct:tref gelu 2)))
  (assert (= 0 (ct:tref (ct:log (ct:ones '(1))) 0))))

(let* ((angles (ct:from-data '((0d0 1d0 2d0)) :dtype :f64))
       (sine (ct:sin angles))
       (cosine (ct:cos angles))
       (out (ct:zeros '(1 3) :dtype :f64)))
  (assert (= 0d0 (ct:tref sine 0 0)))
  (assert (= 1d0 (ct:tref cosine 0 0)))
  (ct:exp! out angles)
  (assert (< (abs (- (ct:tref out 0 1) (exp 1d0))) 1d-14))
  (ct:silu! out angles)
  (ct:gelu! out angles)
  (ct:sin! out angles)
  (ct:cos! out angles)
  (assert (= 1d0 (ct:tref out 0 0)))
  (format t "~&Exponential, RoPE angles and activation out-forms passed.~%"))

(let* ((logits (ct:from-data '((1000 1001 1002) (0 0 0))))
       (probabilities (ct:softmax logits :accumulate :f64))
       (x (ct:from-data '(3 4)))
       (weights (ct:from-data '(1 2))))
  (dotimes (row 2)
    (assert (< (abs (- 1 (ct:tref (ct:sum probabilities :axis -1) row))) 1e-6)))
  (ct:rmsnorm! x x :weights weights :epsilon 0 :accumulate :f64)
  (assert (< (abs (- (ct:tref x 0) (/ 3 (sqrt 12.5)))) 1e-6))
  (assert (< (abs (- (ct:tref x 1) (/ 8 (sqrt 12.5)))) 1e-6))
  (format t "~&Softmax rows and in-place weighted RMSNorm examples passed.~%"))
